export const GRID_GRAPH_NODE_TYPES = [
  'GRID', 'REGION', 'CORRIDOR', 'LINE', 'SUBSTATION', 'BAY', 'TOWER', 'TOWER_COMPONENT', 'CONDUCTOR',
  'INSULATOR', 'HARDWARE', 'PROTECTION_ASSET', 'TRANSFORMER', 'BREAKER', 'DISCONNECTOR', 'TELEMETRY_POINT',
  'DRONE', 'MISSION', 'INSPECTION', 'IMAGE', 'VIDEO', 'FRAME', 'DEFECT', 'CONDITION', 'RISK', 'WORK_ORDER',
  'MAINTENANCE_EVENT', 'ENGINEER', 'TEAM', 'CONTRACTOR', 'LOCATION', 'WEATHER_EVENT', 'OUTAGE', 'INCIDENT',
  'DOCUMENT', 'STANDARD',
  // ---- FINANCE INTELLIGENCE PHASE 01 NODES ----
  'FINANCE_SOURCE', 'FINANCE_BATCH', 'FINANCE_RECORD',
  'FINANCIAL_PERIOD', 'CHART_OF_ACCOUNTS', 'ACCOUNT', 'COST_CENTRE', 'PROFIT_CENTRE', 'DEPARTMENT',
  'BUDGET', 'BUDGET_LINE', 'BUDGET_REVISION', 'BUDGET_ALLOCATION',
  'COMMITMENT', 'ENCUMBRANCE', 'INVOICE', 'PAYMENT', 'RECEIPT',
  'JOURNAL', 'JOURNAL_ENTRY', 'EXPENSE', 'REVENUE',
  'FUNDING', 'GRANT', 'LOAN', 'LIABILITY', 'RECEIVABLE', 'PAYABLE',
  'CASH_ACCOUNT', 'BANK_TRANSACTION',
  'ASSET_VALUE', 'DEPRECIATION', 'CAPEX', 'OPEX',
  'PROJECT_FINANCE', 'PROJECT_COST', 'COST_TO_COMPLETE',
  'FINANCIAL_RISK', 'FINANCIAL_METRIC', 'FINANCIAL_FORECAST',
  'FINANCIAL_DECISION', 'FINANCIAL_REPORT',
  'FINANCE_DATA_QUALITY', 'FINANCE_DATA_PROFILE', 'FINANCE_LINEAGE', 'FINANCE_MAPPING'
] as const;

export const GRID_GRAPH_EDGE_TYPES = [
  'LINE_CONTAINS_TOWER',
  'TOWER_HAS_COMPONENT',
  'COMPONENT_HAS_DEFECT',
  'DEFECT_OBSERVED_IN',
  'OBSERVATION_CAPTURED_BY',
  'MISSION_INSPECTS',
  'MISSION_FOLLOWS',
  'ASSET_LOCATED_AT',
  'ASSET_CONNECTED_TO',
  'ASSET_DEPENDS_ON',
  'DEFECT_AFFECTS',
  'DEFECT_PRECEDES',
  'DEFECT_WORSENED_TO',
  'DEFECT_REPAIRED_BY',
  'WORK_ORDER_RESOLVES',
  'ENGINEER_REVIEWED',
  'STANDARD_GOVERNS',
  'INCIDENT_ASSOCIATED_WITH',
  // ---- FINANCE INTELLIGENCE PHASE 01 EDGES ----
  // Cross-module relationships (Finance ↔ Enterprise Ontology)
  'BUDGET_ALLOCATED_TO_PROJECT',
  'BUDGET_LINE_BELONGS_TO_BUDGET',
  'BUDGET_REVISION_AMENDS_BUDGET',
  'COMMITMENT_RELATES_TO_CONTRACT',
  'COMMITMENT_AGAINST_BUDGET',
  'INVOICE_RELATES_TO_COMMITMENT',
  'INVOICE_FOR_SUPPLIER',
  'PAYMENT_SETTLES_INVOICE',
  'PAYMENT_FROM_CASH_ACCOUNT',
  'PROJECT_COST_BELONGS_TO_PROJECT',
  'CAPEX_CAPITALIZES_ASSET',
  'OPEX_RELATES_TO_DEPARTMENT',
  'OPEX_RELATES_TO_ASSET',
  'OPEX_RELATES_TO_PROJECT',
  'PROJECT_FINANCE_FUNDS_PROJECT',
  'FINANCIAL_RISK_AFFECTS_PROJECT',
  'FINANCIAL_RISK_AFFECTS_BUDGET',
  // Source / lineage edges
  'BATCH_FROM_SOURCE',
  'RECORD_FROM_BATCH',
  'LINEAGE_DERIVED_FROM',
  'MAPPING_BETWEEN_ENTITIES',
  'QUALITY_SCORES_ENTITY',
  // Finance ↔ other KETRACO domains
  'FINANCE_RECORD_RELATES_TO_PROJECT',
  'FINANCE_RECORD_RELATES_TO_SUPPLIER',
  'FINANCE_RECORD_RELATES_TO_ASSET',
  'FINANCE_RECORD_RELATES_TO_CONTRACT',
  'FINANCE_RECORD_RELATES_TO_DEPARTMENT',
  'FINANCE_REPORT_COVERS_PERIOD',
  'FORECAST_FOR_PERIOD'
] as const;

export const GRID_GRAPH_SCHEMA = {
  nodeTypes: GRID_GRAPH_NODE_TYPES,
  relationshipTypes: GRID_GRAPH_EDGE_TYPES,
  sourceOfTruth: 'Transactional database is canonical. Graph is derived and reconciled via immutable events.',
  rules: [
    'Every asset must carry a unique identifier and spatial metadata.',
    'Every defect must be linked to both asset and inspection evidence.',
    'Every workflow or risk object must be traceable to an approval or historical baseline.',
    'Graph writes are replayable and must be synchronized through event-driven reconciliation.'
  ]
} as const;
