import {
  MasterProjectSummary,
  ProgramItem,
  WorkPackageItem,
  MilestoneItem,
  DependencyChainNode
} from '../types';

export const MASTER_PROJECTS: MasterProjectSummary[] = [
  {
    id: 'mombasa',
    code: 'KET-PDS-0042',
    name: 'Mombasa 400kV Ring & Interconnector',
    voltage: '400kV',
    status: 'AT_RISK',
    stage: 'Construction',
    progress: 53.4,
    confidence: 81.7,
    lengthKm: 182,
    substations: 'Rabai 400/220kV, Dongo Kundu 220/132kV, Mariakani 400kV',
    epcContractor: 'Larsen & Toubro / Sterling & Wilson JV',
    approvedBudget: 'KES 6.10B',
    spentBudget: 'KES 3.42B',
    eacBudget: 'KES 6.42B',
    varianceEac: '+KES 320M (+5.2%)',
    forecastCompletion: '28 Nov 2026',
    baselineCompletion: '14 Nov 2026',
    delayDays: 14,
    pmName: 'Eng. David Gitau',
    leadEngineer: 'Eng. Sarah Ochieng',
    programId: 'prog-coast',
    priority: 'STRATEGIC'
  },
  {
    id: 'lamu',
    code: 'KET-PDS-0036',
    name: 'Lamu - Isiolo 400kV Transmission Corridor',
    voltage: '400kV',
    status: 'HEALTHY',
    stage: 'Construction',
    progress: 72.0,
    confidence: 94.0,
    lengthKm: 320,
    substations: 'Lamu Substation, Garissa 400/220kV, Isiolo 400kV',
    epcContractor: 'PowerChina International',
    approvedBudget: 'KES 11.40B',
    spentBudget: 'KES 7.80B',
    eacBudget: 'KES 11.52B',
    varianceEac: '+KES 120M (+1.1%)',
    forecastCompletion: '15 Aug 2026',
    baselineCompletion: '15 Aug 2026',
    delayDays: 0,
    pmName: 'Eng. Paul Kiptoo',
    leadEngineer: 'Eng. Brian Ndwiga',
    programId: 'prog-lapsset',
    priority: 'NATIONAL_CRITICAL'
  },
  {
    id: 'rift',
    code: 'KET-PDS-0055',
    name: 'Rift Valley 220kV Geothermal Evacuation',
    voltage: '220kV',
    status: 'AT_RISK',
    stage: 'Construction',
    progress: 58.2,
    confidence: 82.0,
    lengthKm: 140,
    substations: 'Olkaria IV 220kV, Suswa 400/220kV, Narok 132kV',
    epcContractor: 'KEC International Ltd',
    approvedBudget: 'KES 4.80B',
    spentBudget: 'KES 2.95B',
    eacBudget: 'KES 4.95B',
    varianceEac: '+KES 150M (+3.1%)',
    forecastCompletion: '12 Dec 2026',
    baselineCompletion: '04 Dec 2026',
    delayDays: 8,
    pmName: 'Eng. Grace Wanjiku',
    leadEngineer: 'Eng. Moses Chebet',
    programId: 'prog-western',
    priority: 'STRATEGIC'
  },
  {
    id: 'kisumu',
    code: 'KET-PDS-0029',
    name: 'Kisumu - Lessos 220kV Grid Reinforcement',
    voltage: '220kV',
    status: 'HEALTHY',
    stage: 'Commissioning',
    progress: 84.6,
    confidence: 91.2,
    lengthKm: 98,
    substations: 'Lessos 220/132kV, Muhoroni 132kV, Mamboleo 220/33kV',
    epcContractor: 'Nari Group Corporation',
    approvedBudget: 'KES 3.90B',
    spentBudget: 'KES 3.65B',
    eacBudget: 'KES 3.88B',
    varianceEac: '-KES 20M (-0.5%)',
    forecastCompletion: '30 Sep 2026',
    baselineCompletion: '30 Sep 2026',
    delayDays: 0,
    pmName: 'Eng. Joseph Otieno',
    leadEngineer: 'Eng. Faith Achieng',
    programId: 'prog-western',
    priority: 'REGIONAL'
  },
  {
    id: 'nairobi',
    code: 'KET-PDS-0018',
    name: 'Nairobi Metropolitan 132kV Ring System',
    voltage: '132kV',
    status: 'HEALTHY',
    stage: 'Commissioning',
    progress: 92.4,
    confidence: 96.5,
    lengthKm: 74,
    substations: 'Embakasi 220/132kV, Dandora 132kV, Ngong 66kV',
    epcContractor: 'TBEA Co. Ltd',
    approvedBudget: 'KES 5.20B',
    spentBudget: 'KES 4.88B',
    eacBudget: 'KES 5.15B',
    varianceEac: '-KES 50M (-0.9%)',
    forecastCompletion: '15 Oct 2026',
    baselineCompletion: '15 Oct 2026',
    delayDays: 0,
    pmName: 'Eng. Lucy Mwangi',
    leadEngineer: 'Eng. Peter Kamau',
    programId: 'prog-metro',
    priority: 'NATIONAL_CRITICAL'
  },
  {
    id: 'tana',
    code: 'KET-PDS-0071',
    name: 'Tana River 220kV Hydro Intertie',
    voltage: '220kV',
    status: 'AT_RISK',
    stage: 'Land/Wayleave',
    progress: 41.0,
    confidence: 76.0,
    lengthKm: 115,
    substations: 'Kiambere 220kV, Garissa 220/132kV',
    epcContractor: 'Sterling & Wilson Ltd',
    approvedBudget: 'KES 3.40B',
    spentBudget: 'KES 1.45B',
    eacBudget: 'KES 3.62B',
    varianceEac: '+KES 220M (+6.5%)',
    forecastCompletion: '14 Feb 2027',
    baselineCompletion: '24 Jan 2027',
    delayDays: 21,
    pmName: 'Eng. Hassan Abdi',
    leadEngineer: 'Eng. Kevin Mutua',
    programId: 'prog-eastern',
    priority: 'REGIONAL'
  },
  {
    id: 'western',
    code: 'KET-PDS-0068',
    name: 'Western Grid 132kV Resiliency Corridor',
    voltage: '132kV',
    status: 'HEALTHY',
    stage: 'Construction',
    progress: 68.3,
    confidence: 88.0,
    lengthKm: 124,
    substations: 'Webuye 132/33kV, Bungoma 132kV, Malaba 132/33kV',
    epcContractor: 'Siemens Energy / local sub JV',
    approvedBudget: 'KES 2.80B',
    spentBudget: 'KES 1.95B',
    eacBudget: 'KES 2.82B',
    varianceEac: '+KES 20M (+0.7%)',
    forecastCompletion: '05 Jan 2027',
    baselineCompletion: '31 Dec 2026',
    delayDays: 5,
    pmName: 'Eng. Alice Barasa',
    leadEngineer: 'Eng. Dan Wekesa',
    programId: 'prog-western',
    priority: 'REGIONAL'
  },
  {
    id: 'south',
    code: 'KET-PDS-0084',
    name: 'South Coast 220kV Regional Backbone',
    voltage: '220kV',
    status: 'CRITICAL',
    stage: 'Procurement',
    progress: 35.0,
    confidence: 68.0,
    lengthKm: 88,
    substations: 'Diani 132kV, Ukunda 220/132kV, Lunga Lunga 132kV',
    epcContractor: 'EPC Tender Under Adjudication',
    approvedBudget: 'KES 2.90B',
    spentBudget: 'KES 0.72B',
    eacBudget: 'KES 3.15B',
    varianceEac: '+KES 250M (+8.6%)',
    forecastCompletion: '28 Apr 2027',
    baselineCompletion: '24 Mar 2027',
    delayDays: 35,
    pmName: 'Eng. Omar Mwashetani',
    leadEngineer: 'Eng. Jane Muriuki',
    programId: 'prog-coast',
    priority: 'STRATEGIC'
  }
];

export const PROGRAMS_DATA: ProgramItem[] = [
  {
    id: 'prog-coast',
    code: 'PRG-COAST-400',
    name: 'Coast Regional Transmission Backbone',
    description: 'Securing industrial power transmission to Dongo Kundu SEZ, Mombasa Port and South Coast interconnector.',
    projectsCount: 3,
    childProjects: ['Mombasa 400kV Ring & Interconnector', 'South Coast 220kV Regional Backbone', 'Rabai Substation Upgrade'],
    totalBudget: 'KES 10.40B',
    totalEac: 'KES 11.02B',
    combinedProgress: 56.8,
    health: 'AT_RISK',
    sharedResources: ['Lead Substation Testing Specialist', 'Heavy Piling Rig 04', 'Wayleave Legal Arbitrator'],
    sharedSuppliers: ['TBEA Transformers', 'Jindal Steel & Power', 'Nexans Conductors'],
    sharedContractors: ['Larsen & Toubro', 'Sterling & Wilson'],
    programRisksCount: 4,
    benefits: ['Loss reduction of 42 MW', 'N-1 reliability for Mombasa Island', 'Export capacity to Tanzania grid']
  },
  {
    id: 'prog-lapsset',
    code: 'PRG-LAPSSET-400',
    name: 'LAPSSET Corridor National Energy Highway',
    description: 'Strategic energy integration of Lamu Port, Isiolo logistics hub and Kenya-Ethiopia interconnector.',
    projectsCount: 2,
    childProjects: ['Lamu - Isiolo 400kV Transmission Corridor', 'Isiolo Substation 400/220kV Extension'],
    totalBudget: 'KES 14.80B',
    totalEac: 'KES 15.05B',
    combinedProgress: 69.4,
    health: 'HEALTHY',
    sharedResources: ['Desert Survey Crew 02', 'High-mast Stringing Tensioner A'],
    sharedSuppliers: ['PowerChina Supply Unit', 'Baosteel Tower Steel'],
    sharedContractors: ['PowerChina International'],
    programRisksCount: 2,
    benefits: ['Unlocks 500 MW renewable dispatch', 'Electrifies Lamu Special Economic Zone']
  },
  {
    id: 'prog-western',
    code: 'PRG-WEST-220',
    name: 'Western Kenya Renewable Evacuation Program',
    description: 'High-voltage evacuation of geothermal and hydro energy to western industrial hubs and Uganda intertie.',
    projectsCount: 4,
    childProjects: ['Kisumu - Lessos 220kV Grid Reinforcement', 'Rift Valley 220kV Geothermal Evacuation', 'Western Grid 132kV Resiliency Corridor', 'Olkaria IV Bay Addition'],
    totalBudget: 'KES 12.60B',
    totalEac: 'KES 12.80B',
    combinedProgress: 70.8,
    health: 'HEALTHY',
    sharedResources: ['Chief Commissioning Engineer', 'Protection Relay Engineer'],
    sharedSuppliers: ['Nari Group', 'KEC India', 'Apar Industries'],
    sharedContractors: ['KEC International Ltd', 'Nari Group Corporation', 'Siemens Energy'],
    programRisksCount: 3,
    benefits: ['Stabilizes Lake Basin voltage swings', 'Enables 120 MW cross-border wheeling with UETCL']
  },
  {
    id: 'prog-metro',
    code: 'PRG-NAIROBI-RING',
    name: 'Nairobi Metropolitan 132kV Grid Modernization',
    description: 'Underground cabling and compact GIS substations securing power reliability for the capital city.',
    projectsCount: 3,
    childProjects: ['Nairobi Metropolitan 132kV Ring System', 'City Centre 66kV Underground Feeder', 'Dandora Substation Modernization'],
    totalBudget: 'KES 8.90B',
    totalEac: 'KES 8.85B',
    combinedProgress: 88.2,
    health: 'HEALTHY',
    sharedResources: ['Urban Cable Splicing Unit', 'GIS SF6 Testing Van'],
    sharedSuppliers: ['TBEA', 'Prysmian Cables'],
    sharedContractors: ['TBEA Co. Ltd'],
    programRisksCount: 1,
    benefits: ['Zero single-point failures for Central Business District', 'Reduces urban technical losses by 3.8%']
  }
];

export const WORK_PACKAGES_DATA: WorkPackageItem[] = [
  {
    id: 'wp-01',
    projectId: 'mombasa',
    code: 'WP-MOM-01',
    title: 'Geotechnical Investigation & Tower Pad Survey',
    scope: 'Cadastral centerline survey and 182km soil boring analysis for 412 tower foundation footings.',
    owner: 'Eng. Brian Ndwiga',
    startDate: '12 Jan 2025',
    endDate: '24 Apr 2025',
    progress: 100,
    materials: ['Survey benchmarks', 'Borehole core samples'],
    contractor: 'Geotech Solutions Kenya Ltd',
    dependencies: ['Wayleave Access Approval'],
    cost: 'KES 94.0M',
    actualCost: 'KES 92.4M',
    risks: ['Underground coral rock variance in Likoni section'],
    evidenceDocs: ['Geotech Final Report Rev 3', 'Borehole Logs Signed'],
    status: 'COMPLETED'
  },
  {
    id: 'wp-02',
    projectId: 'mombasa',
    code: 'WP-MOM-02',
    title: 'Tower Foundation Piling & Civil Works',
    scope: 'Excavation, reinforcement rebar binding, and concrete casting for 412 transmission tower pads.',
    owner: 'Eng. Kevin Mutua',
    startDate: '01 May 2025',
    endDate: '15 Oct 2026',
    progress: 68.5,
    materials: ['Ready-mix Concrete (Class 30/20)', 'High-yield deformed steel rebar T16/T25'],
    contractor: 'Larsen & Toubro Ltd',
    dependencies: ['WP-MOM-01'],
    cost: 'KES 1.42B',
    actualCost: 'KES 1.05B',
    risks: ['High water table near creek crossing requiring continuous dewatering'],
    evidenceDocs: ['Cube Strength Test Certificates (Batch 14-29)', 'Foundation Pour Records'],
    status: 'IN_PROGRESS'
  },
  {
    id: 'wp-03',
    projectId: 'mombasa',
    code: 'WP-MOM-03',
    title: 'Tower Steel Fabrication & Erection',
    scope: 'Assembly and hydraulic torque tightening of 400kV double-circuit lattice steel towers.',
    owner: 'Eng. David Gitau',
    startDate: '15 Aug 2025',
    endDate: '10 Nov 2026',
    progress: 52.0,
    materials: ['Galvanized angle steel (Grade S355)', 'High tensile bolts & step bolts'],
    contractor: 'Larsen & Toubro Ltd',
    dependencies: ['WP-MOM-02'],
    cost: 'KES 1.85B',
    actualCost: 'KES 960M',
    risks: ['Supplier shipment delay on 30T leg extensions for swamp towers'],
    evidenceDocs: ['Factory Galvanizing Inspection Certificate', 'Tower Verticality Survey Records'],
    status: 'IN_PROGRESS'
  },
  {
    id: 'wp-04',
    projectId: 'mombasa',
    code: 'WP-MOM-04',
    title: 'Conductor & OPGW Stringing',
    scope: 'Tension stringing of AAAC 400mm² Zebra conductors and 24-core Optical Ground Wire.',
    owner: 'Eng. Sarah Ochieng',
    startDate: '01 Oct 2025',
    endDate: '18 Nov 2026',
    progress: 38.0,
    materials: ['AAAC Zebra Conductors (540km)', 'OPGW Fibre Cable', 'Composite Silicone Insulators'],
    contractor: 'Sterling & Wilson Ltd',
    dependencies: ['WP-MOM-03'],
    cost: 'KES 1.15B',
    actualCost: 'KES 440M',
    risks: ['Highway crossing permission over Mombasa-Nairobi SGR/Expressway'],
    evidenceDocs: ['KeNHA Road Crossing Permit', 'KRC Rail Clearance Agreement'],
    status: 'IN_PROGRESS'
  },
  {
    id: 'wp-05',
    projectId: 'mombasa',
    code: 'WP-MOM-05',
    title: 'Substation Transformers & Switchgear',
    scope: 'Installation and testing of two 400/220/33kV 200MVA autotransformers at Mariakani & Rabai.',
    owner: 'Eng. Joseph Otieno',
    startDate: '10 Nov 2025',
    endDate: '22 Nov 2026',
    progress: 44.0,
    materials: ['200MVA Autotransformer (TBEA)', '400kV SF6 Circuit Breakers', 'Current Transformers'],
    contractor: 'Larsen & Toubro Ltd',
    dependencies: ['WP-MOM-02'],
    cost: 'KES 1.25B',
    actualCost: 'KES 650M',
    risks: ['Transformer T-204 Mumbai dry-dock reinspection delayed +14 days'],
    evidenceDocs: ['Factory Acceptance Test (FAT) Protocol', 'Oil Dissolved Gas Analysis Pre-shipment'],
    status: 'BLOCKED'
  },
  {
    id: 'wp-06',
    projectId: 'mombasa',
    code: 'WP-MOM-06',
    title: 'Protection, SCADA & Telecommunication',
    scope: 'IEC 61850 substation automation, line differential relays and fiber tele-protection integration.',
    owner: 'Eng. Lucy Mwangi',
    startDate: '15 Jan 2026',
    endDate: '25 Nov 2026',
    progress: 25.0,
    materials: ['Microprocessor Protection Relays', 'SCADA RTUs', 'Fiber Optic Patch Panels'],
    contractor: 'ABB Power Grids / Hitachi',
    dependencies: ['WP-MOM-05'],
    cost: 'KES 290M',
    actualCost: 'KES 80M',
    risks: ['National Control Centre (NCC) tele-protection protocol firmware validation'],
    evidenceDocs: ['SAS Architecture Schematic Rev 2', 'Relay Setting Calculation Document'],
    status: 'IN_PROGRESS'
  }
];

export const MILESTONES_DATA: MilestoneItem[] = [
  {
    id: 'ms-01',
    projectId: 'mombasa',
    code: 'MS-MOM-01',
    name: 'Route Geotech & Final Profile Signoff',
    baseline: '15 Apr 2025',
    planned: '15 Apr 2025',
    forecast: '15 Apr 2025',
    actual: '12 Apr 2025',
    varianceDays: 0,
    predecessor: 'Contract Effective Date',
    successor: 'MS-MOM-02',
    owner: 'Eng. Brian Ndwiga',
    confidence: 100,
    isCritical: false,
    status: 'COMPLETED'
  },
  {
    id: 'ms-02',
    projectId: 'mombasa',
    code: 'MS-MOM-02',
    name: 'Substructure Foundations 50% Milestone',
    baseline: '20 Jul 2025',
    planned: '20 Jul 2025',
    forecast: '28 Jul 2025',
    actual: '28 Jul 2025',
    varianceDays: -8,
    predecessor: 'MS-MOM-01',
    successor: 'MS-MOM-03',
    owner: 'Eng. Kevin Mutua',
    confidence: 100,
    isCritical: true,
    status: 'COMPLETED'
  },
  {
    id: 'ms-03',
    projectId: 'mombasa',
    code: 'MS-MOM-03',
    name: 'Tower Erection Section 1 (Towers 1-180)',
    baseline: '15 Oct 2025',
    planned: '15 Oct 2025',
    forecast: '24 Oct 2025',
    actual: '24 Oct 2025',
    varianceDays: -9,
    predecessor: 'MS-MOM-02',
    successor: 'MS-MOM-04',
    owner: 'Eng. David Gitau',
    confidence: 100,
    isCritical: true,
    status: 'COMPLETED'
  },
  {
    id: 'ms-04',
    projectId: 'mombasa',
    code: 'MS-MOM-04',
    name: '400kV Transformer T-204 Delivery at Site',
    baseline: '12 Sep 2026',
    planned: '12 Sep 2026',
    forecast: '26 Sep 2026',
    varianceDays: -14,
    predecessor: 'MS-MOM-03',
    successor: 'MS-MOM-06',
    owner: 'Eng. Joseph Otieno',
    confidence: 78,
    isCritical: true,
    status: 'DELAYED'
  },
  {
    id: 'ms-05',
    projectId: 'mombasa',
    code: 'MS-MOM-05',
    name: 'Conductor Stringing Section 2 Completion',
    baseline: '15 Oct 2026',
    planned: '15 Oct 2026',
    forecast: '22 Oct 2026',
    varianceDays: -7,
    predecessor: 'MS-MOM-03',
    successor: 'MS-MOM-07',
    owner: 'Eng. Sarah Ochieng',
    confidence: 84,
    isCritical: false,
    status: 'ON_TRACK'
  },
  {
    id: 'ms-06',
    projectId: 'mombasa',
    code: 'MS-MOM-06',
    name: 'Substation Transformer Cold Commissioning',
    baseline: '28 Oct 2026',
    planned: '28 Oct 2026',
    forecast: '09 Nov 2026',
    varianceDays: -12,
    predecessor: 'MS-MOM-04',
    successor: 'MS-MOM-08',
    owner: 'Eng. Joseph Otieno',
    confidence: 80,
    isCritical: true,
    status: 'UPCOMING'
  },
  {
    id: 'ms-07',
    projectId: 'mombasa',
    code: 'MS-MOM-07',
    name: 'Full Line High Voltage Dielectric Testing',
    baseline: '05 Nov 2026',
    planned: '05 Nov 2026',
    forecast: '17 Nov 2026',
    varianceDays: -12,
    predecessor: 'MS-MOM-05',
    successor: 'MS-MOM-08',
    owner: 'Eng. Moses Chebet',
    confidence: 82,
    isCritical: true,
    status: 'UPCOMING'
  },
  {
    id: 'ms-08',
    projectId: 'mombasa',
    code: 'MS-MOM-08',
    name: 'Commercial Grid Energization & COD',
    baseline: '14 Nov 2026',
    planned: '14 Nov 2026',
    forecast: '28 Nov 2026',
    varianceDays: -14,
    predecessor: 'MS-MOM-06, MS-MOM-07',
    successor: 'Commercial Operations',
    owner: 'Eng. David Gitau',
    confidence: 81.7,
    isCritical: true,
    status: 'UPCOMING'
  }
];

export const DEPENDENCY_CHAIN_DATA: DependencyChainNode[] = [
  {
    id: 'dep-proj',
    tier: 'Project',
    label: 'Mombasa 400kV Ring & Interconnector',
    code: 'KET-PDS-0042',
    status: 'AT_RISK',
    varianceDays: -14,
    blockers: ['Transformer T-204 delivery lag', 'Wayleave valuation escrow in Mariakani'],
    downstreamImpacts: ['Rabai 400kV Energization', 'Dongo Kundu SEZ Power Date'],
    owner: 'Eng. David Gitau'
  },
  {
    id: 'dep-ms-04',
    tier: 'Milestone',
    label: '400kV Transformer T-204 Delivery at Site',
    code: 'MS-MOM-04',
    status: 'CRITICAL',
    varianceDays: -14,
    blockers: ['Factory QC reinspection in Mumbai dry-dock', 'Heavy haul low-loader permit KeNHA'],
    downstreamImpacts: ['Substation Cold Commissioning (delayed 12d)', 'Grid Energization (delayed 14d)'],
    owner: 'Eng. Joseph Otieno'
  },
  {
    id: 'dep-mat-01',
    tier: 'Material',
    label: '200MVA 400/220kV Autotransformer T-204',
    code: 'MAT-XFMR-400',
    status: 'CRITICAL',
    varianceDays: -14,
    blockers: ['Bushing oil leakage during dry test', 'Customs clearance bonded warehouse entry'],
    downstreamImpacts: ['MS-MOM-04 Delivery on Pad', 'Civil oil containment gravel fill'],
    owner: 'Eng. Faith Achieng'
  },
  {
    id: 'dep-sup-01',
    tier: 'Supplier',
    label: 'TBEA Hengyang Transformer Co.',
    code: 'SUP-TBEA-01',
    status: 'AT_RISK',
    varianceDays: -10,
    blockers: ['Port container vessel booking slip from Nhava Sheva'],
    downstreamImpacts: ['Vessel MSC Aurora sailing schedule', 'Mombasa Berth 4 unloading priority'],
    owner: 'Procurement Directorate'
  },
  {
    id: 'dep-cnt-01',
    tier: 'Contract',
    label: 'EPC Contract Lot 2: Rabai Substation Works',
    code: 'CNT-KET-0042-02',
    status: 'HEALTHY',
    varianceDays: 0,
    blockers: ['Letter of Credit 60-day extension awaiting Treasury exchequer concurrence'],
    downstreamImpacts: ['Supplier stage payment release', 'Manufacturer bill of lading surrender'],
    owner: 'Commercial Contracts Manager'
  },
  {
    id: 'dep-shp-01',
    tier: 'Shipment',
    label: 'Vessel MSC Aurora / Voyage 264A (Heavy Lift)',
    code: 'SHP-MOM-902',
    status: 'AT_RISK',
    varianceDays: -8,
    blockers: ['Monsoon weather route diversion in Arabian Sea'],
    downstreamImpacts: ['Arrival ETA Mombasa Port shifted from 12 Sep to 20 Sep'],
    owner: 'Logistics Liaison Officer'
  },
  {
    id: 'dep-ins-01',
    tier: 'Installation',
    label: 'Transformer Pad Rigging & Jacking to Plinth',
    code: 'INS-PAD-04',
    status: 'AT_RISK',
    varianceDays: -12,
    blockers: ['Crane 250T hydraulic rental window booked for 22 Sep'],
    downstreamImpacts: ['Radiator assembly and oil filling cycle (14 days)'],
    owner: 'Resident Engineer'
  },
  {
    id: 'dep-com-01',
    tier: 'Commissioning',
    label: 'Commercial Grid Energization (COD)',
    code: 'MS-MOM-08',
    status: 'AT_RISK',
    varianceDays: -14,
    blockers: ['Requires completed dielectric testing and EPRA safety certificate'],
    downstreamImpacts: ['KES 42M deemed generation loss if COD exceeds Nov 30'],
    owner: 'Director Project Management'
  }
];

export const MASTER_WORK_PACKAGES = WORK_PACKAGES_DATA;
export const MASTER_MILESTONES = MILESTONES_DATA;

export interface MasterDependencyItem {
  id: string;
  projectId: string;
  type: string;
  lagDays: number;
  criticality: 'CRITICAL' | 'HIGH' | 'MEDIUM';
  status: 'RESOLVED' | 'ACTIVE' | 'BLOCKED';
  predecessorName: string;
  successorName: string;
  description: string;
}

export const MASTER_DEPENDENCIES: MasterDependencyItem[] = [
  {
    id: '1',
    projectId: 'mombasa',
    type: 'FS',
    lagDays: 0,
    criticality: 'CRITICAL',
    status: 'ACTIVE',
    predecessorName: 'NLC Gazettement & Valuation Escrow',
    successorName: 'Tower Foundation Piling & Civils (Lot 1)',
    description: 'Statutory Gazettement under Section 107 must be gazetted before contractor access to private land parcels in Mariakani corridor.'
  },
  {
    id: '2',
    projectId: 'mombasa',
    type: 'SS',
    lagDays: 14,
    criticality: 'CRITICAL',
    status: 'ACTIVE',
    predecessorName: 'Tower Foundation Piling & Civils',
    successorName: 'Tower Steel Fabrication & Erection',
    description: 'Requires 28-day concrete cube compression strength verification before hydraulic torque erection of heavy tension towers.'
  },
  {
    id: '3',
    projectId: 'mombasa',
    type: 'FS',
    lagDays: 5,
    criticality: 'CRITICAL',
    status: 'BLOCKED',
    predecessorName: 'Autotransformer T-204 Mumbai Delivery',
    successorName: 'Rabai Substation Bay Integration & Wiring',
    description: 'Factory QC reinspection in Mumbai dry dock currently slips site plinth jacking window by 14 days.'
  },
  {
    id: '4',
    projectId: 'mombasa',
    type: 'FF',
    lagDays: 7,
    criticality: 'HIGH',
    status: 'ACTIVE',
    predecessorName: 'Tower Steel Erection',
    successorName: 'Conductor & OPGW Stringing',
    description: 'Continuous rolling tensioner puller crew must maintain minimum 10 erected towers ahead of conductor pulling.'
  },
  {
    id: '5',
    projectId: 'mombasa',
    type: 'FS',
    lagDays: 0,
    criticality: 'MEDIUM',
    status: 'RESOLVED',
    predecessorName: 'KRC SGR Rail Crossing Approval',
    successorName: 'Stringing Over Rail Corridor Section 4',
    description: 'Kenya Railways Corporation track possession safety permit obtained for nocturnal stringing hours.'
  },
  {
    id: '6',
    projectId: 'mombasa',
    type: 'FS',
    lagDays: 3,
    criticality: 'CRITICAL',
    status: 'ACTIVE',
    predecessorName: 'National Control Centre (NCC) SAS RTU Tele-Protection',
    successorName: 'High-Voltage Pre-Commissioning & Grid Energization',
    description: 'End-to-end tele-protection signalling channel test required between NCC Nairobi and Rabai 400kV control room.'
  }
];
