import { 
  GridAsset, 
  TransmissionLine, 
  GridAlarm, 
  GridEvent, 
  KpiFamily, 
  AiInvestigationInsight,
  DataFreshness
} from './types';

const REFERENCE_SOURCE_VERSION = 'KETRACO public reference layer (ArcGIS FeatureServer)';

const withReferenceProvenance = (source: string, publishedAt?: string | null) => ({
  source,
  sourceVersion: REFERENCE_SOURCE_VERSION,
  sourceRetrievedAt: new Date().toISOString(),
  sourcePublishedAt: publishedAt ?? null,
  confidence: 98,
  verificationStatus: 'REFERENCE' as const
});

const annotateReferenceTelemetry = (asset: GridAsset) => {
  for (const point of Object.values(asset.telemetry)) {
    if (!point) continue;
    point.freshness = 'REFERENCE' as DataFreshness;
    point.provenance = withReferenceProvenance(point.source, null);
  }
};

// Authoritative KETRACO Substations Dataset
export const CANONICAL_SUBSTATIONS: Record<string, GridAsset> = {
  suswa: {
    id: 'suswa',
    name: 'Suswa 500kV / 400kV EHV Hub',
    code: 'SSW-500-01',
    type: 'SUBSTATION',
    voltageLevelKV: 500,
    region: 'RIFT_VALLEY',
    county: 'Narok',
    scadaId: 'SCD-KTR-SSW-01',
    gisId: 'GIS-NODE-88412',
    eamId: 'EAM-SAP-EQ-10029',
    engineeringId: 'ENG-DWG-500-SSW-A',
    confidence: 98.4,
    reconciliationStatus: 'VERIFIED',
    latitude: -1.0543,
    longitude: 36.3532,
    elevationM: 1890,
    coordinates: { x: 310, y: 320 },
    state: 'WARNING',
    telemetry: {
      activePowerMW: { value: 1145, unit: 'MW', timestamp: new Date().toISOString(), source: 'SCADA_EMS', quality: 'GOOD', freshness: 'LIVE', confidence: 99 },
      reactivePowerMVAR: { value: 182, unit: 'MVAR', timestamp: new Date().toISOString(), source: 'SCADA_EMS', quality: 'GOOD', freshness: 'LIVE', confidence: 98 },
      voltageKV: { value: 508.2, unit: 'kV', timestamp: new Date().toISOString(), source: 'WAMS_PMU', quality: 'GOOD', freshness: 'LIVE', confidence: 99.5 },
      frequencyHz: { value: 50.02, unit: 'Hz', timestamp: new Date().toISOString(), source: 'WAMS_PMU', quality: 'GOOD', freshness: 'LIVE', confidence: 99.9 },
      thermalLoadingPct: { value: 81.4, unit: '%', timestamp: new Date().toISOString(), source: 'SCADA_EMS', quality: 'GOOD', freshness: 'LIVE', confidence: 97 },
      transformerOilTempC: { value: 68.5, unit: '°C', timestamp: new Date().toISOString(), source: 'SCADA_EMS', quality: 'GOOD', freshness: 'LIVE', confidence: 96 },
      sf6PressureBar: { value: 6.2, unit: 'bar', timestamp: new Date().toISOString(), source: 'SCADA_EMS', quality: 'GOOD', freshness: 'LIVE', confidence: 98 },
      powerFactor: { value: 0.98, unit: 'PF', timestamp: new Date().toISOString(), source: 'SCADA_EMS', quality: 'GOOD', freshness: 'LIVE', confidence: 99 }
    },
    ratedCapacityMVA: 1500,
    currentLoadMW: 1145,
    peakLoadMW: 1320,
    healthScore: 78,
    riskScore: 68,
    criticalityScore: 10,
    nMinusOneRedundant: true,
    singlePointOfFailure: false,
    connectedLines: ['tl_ssw_olk', 'tl_ssw_isy', 'tl_ssw_nbn', 'tl_hvdc_eth_ken', 'tl_loy_ssw'],
    connectedSubstations: ['olkaria', 'isinya', 'nairobi_north', 'loiyangalani', 'moyale_hvdc'],
    downstreamNodes: ['nairobi_north', 'isinya', 'nairobi_ring'],
    upstreamNodes: ['olkaria', 'loiyangalani', 'moyale_hvdc'],
    alternativePaths: ['olkaria -> lessos -> kisumu', 'isinya -> mariakani -> rabai'],
    transformersCount: 4,
    baysCount: 16,
    breakersCount: 28,
    protectionRelaysCount: 42,
    sources: ['SCADA_EMS', 'GIS_POSTGIS', 'WAMS_PMU', 'EAM_SAP'],
    lastUpdated: '1 sec ago',
    maintenanceForecast: 'Auto-Transformer T2 oil filtration scheduled in 6 days.',
    activeProjects: ['KET-TR-041 Suswa Reactive Power Upgrade', 'Lot 4 500kV HVDC Converter Optimization'],
    activeTenders: ['KETRACO-SCM-2026-T4 (Auto-Transformer Spares)', 'OPGW Monitoring Interface'],
    contractors: ['Siemens Energy Kenya', 'China Electric Power Equipment Corp']
  },
  olkaria: {
    id: 'olkaria',
    name: 'Olkaria Geothermal Switching Station',
    code: 'OLK-400-01',
    type: 'GENERATOR_INTERFACE',
    voltageLevelKV: 400,
    region: 'RIFT_VALLEY',
    county: 'Nakuru',
    scadaId: 'SCD-KTR-OLK-01',
    gisId: 'GIS-NODE-88415',
    eamId: 'EAM-SAP-EQ-10034',
    engineeringId: 'ENG-DWG-400-OLK-B',
    confidence: 99.2,
    reconciliationStatus: 'VERIFIED',
    latitude: -0.8842,
    longitude: 36.3012,
    elevationM: 1950,
    coordinates: { x: 260, y: 280 },
    state: 'NORMAL',
    telemetry: {
      activePowerMW: { value: 892, unit: 'MW', timestamp: new Date().toISOString(), source: 'SCADA_EMS', quality: 'GOOD', freshness: 'LIVE', confidence: 99 },
      reactivePowerMVAR: { value: 110, unit: 'MVAR', timestamp: new Date().toISOString(), source: 'SCADA_EMS', quality: 'GOOD', freshness: 'LIVE', confidence: 98 },
      voltageKV: { value: 402.1, unit: 'kV', timestamp: new Date().toISOString(), source: 'WAMS_PMU', quality: 'GOOD', freshness: 'LIVE', confidence: 99.7 },
      frequencyHz: { value: 50.01, unit: 'Hz', timestamp: new Date().toISOString(), source: 'WAMS_PMU', quality: 'GOOD', freshness: 'LIVE', confidence: 99.9 },
      thermalLoadingPct: { value: 64.2, unit: '%', timestamp: new Date().toISOString(), source: 'SCADA_EMS', quality: 'GOOD', freshness: 'LIVE', confidence: 98 },
      transformerOilTempC: { value: 54.1, unit: '°C', timestamp: new Date().toISOString(), source: 'SCADA_EMS', quality: 'GOOD', freshness: 'LIVE', confidence: 97 },
      sf6PressureBar: { value: 6.5, unit: 'bar', timestamp: new Date().toISOString(), source: 'SCADA_EMS', quality: 'GOOD', freshness: 'LIVE', confidence: 99 },
      powerFactor: { value: 0.99, unit: 'PF', timestamp: new Date().toISOString(), source: 'SCADA_EMS', quality: 'GOOD', freshness: 'LIVE', confidence: 99 }
    },
    ratedCapacityMVA: 1200,
    currentLoadMW: 892,
    peakLoadMW: 960,
    healthScore: 96,
    riskScore: 14,
    criticalityScore: 9,
    nMinusOneRedundant: true,
    singlePointOfFailure: false,
    connectedLines: ['tl_ssw_olk', 'tl_olk_les'],
    connectedSubstations: ['suswa', 'lessos'],
    downstreamNodes: ['suswa', 'lessos'],
    upstreamNodes: ['olkaria_plants'],
    alternativePaths: ['olkaria -> lessos -> kisumu'],
    transformersCount: 3,
    baysCount: 12,
    breakersCount: 18,
    protectionRelaysCount: 30,
    sources: ['SCADA_EMS', 'GIS_POSTGIS', 'WAMS_PMU'],
    lastUpdated: '1 sec ago',
    maintenanceForecast: 'Nominal baseload dispatch. Semi-annual relay calibration Nov 2026.',
    activeProjects: ['Olkaria IV Switchyard Solid-State Relay Retrofit'],
    activeTenders: ['Protection Relay Calibration Kits'],
    contractors: ['Toshiba Energy Systems', 'East African Cables']
  },
  isinya: {
    id: 'isinya',
    name: 'Isinya 400kV / 220kV Interconnector Substation',
    code: 'ISN-400-01',
    type: 'SUBSTATION',
    voltageLevelKV: 400,
    region: 'CENTRAL',
    county: 'Kajiado',
    scadaId: 'SCD-KTR-ISN-01',
    gisId: 'GIS-NODE-88420',
    eamId: 'EAM-SAP-EQ-10055',
    engineeringId: 'ENG-DWG-400-ISN-01',
    confidence: 97.8,
    reconciliationStatus: 'VERIFIED',
    latitude: -1.6721,
    longitude: 36.8543,
    elevationM: 1650,
    coordinates: { x: 380, y: 390 },
    state: 'NORMAL',
    telemetry: {
      activePowerMW: { value: 720, unit: 'MW', timestamp: new Date().toISOString(), source: 'SCADA_EMS', quality: 'GOOD', freshness: 'LIVE', confidence: 99 },
      reactivePowerMVAR: { value: 85, unit: 'MVAR', timestamp: new Date().toISOString(), source: 'SCADA_EMS', quality: 'GOOD', freshness: 'LIVE', confidence: 97 },
      voltageKV: { value: 399.8, unit: 'kV', timestamp: new Date().toISOString(), source: 'WAMS_PMU', quality: 'GOOD', freshness: 'LIVE', confidence: 99.4 },
      frequencyHz: { value: 50.01, unit: 'Hz', timestamp: new Date().toISOString(), source: 'WAMS_PMU', quality: 'GOOD', freshness: 'LIVE', confidence: 99.9 },
      thermalLoadingPct: { value: 58.0, unit: '%', timestamp: new Date().toISOString(), source: 'SCADA_EMS', quality: 'GOOD', freshness: 'LIVE', confidence: 98 },
      transformerOilTempC: { value: 51.2, unit: '°C', timestamp: new Date().toISOString(), source: 'SCADA_EMS', quality: 'GOOD', freshness: 'LIVE', confidence: 98 },
      sf6PressureBar: { value: 6.4, unit: 'bar', timestamp: new Date().toISOString(), source: 'SCADA_EMS', quality: 'GOOD', freshness: 'LIVE', confidence: 99 },
      powerFactor: { value: 0.97, unit: 'PF', timestamp: new Date().toISOString(), source: 'SCADA_EMS', quality: 'GOOD', freshness: 'LIVE', confidence: 99 }
    },
    ratedCapacityMVA: 1000,
    currentLoadMW: 720,
    peakLoadMW: 840,
    healthScore: 92,
    riskScore: 22,
    criticalityScore: 9,
    nMinusOneRedundant: true,
    singlePointOfFailure: false,
    connectedLines: ['tl_ssw_isy', 'tl_isy_mrk', 'tl_isy_emb'],
    connectedSubstations: ['suswa', 'mariakani', 'nairobi_ring'],
    downstreamNodes: ['nairobi_ring', 'mariakani'],
    upstreamNodes: ['suswa'],
    alternativePaths: ['suswa -> nairobi_north -> nairobi_ring'],
    transformersCount: 3,
    baysCount: 14,
    breakersCount: 22,
    protectionRelaysCount: 36,
    sources: ['SCADA_EMS', 'GIS_POSTGIS', 'WAMS_PMU'],
    lastUpdated: '2 sec ago',
    maintenanceForecast: 'Routine annual transformer dissolved gas analysis (DGA) scheduled.',
    activeProjects: ['Isinya-Namanga 132kV Interconnection Line'],
    activeTenders: ['EHV SF6 Circuit Breaker Refurbishment Modules'],
    contractors: ['KEC International Ltd', 'AEE Power']
  },
  nairobi_north: {
    id: 'nairobi_north',
    name: 'Nairobi North 400kV / 220kV Substation',
    code: 'NBN-400-01',
    type: 'SUBSTATION',
    voltageLevelKV: 400,
    region: 'NAIROBI',
    county: 'Kiambu',
    scadaId: 'SCD-KTR-NBN-01',
    gisId: 'GIS-NODE-88430',
    eamId: 'EAM-SAP-EQ-10060',
    engineeringId: 'ENG-DWG-400-NBN-02',
    confidence: 98.9,
    reconciliationStatus: 'VERIFIED',
    latitude: -1.1894,
    longitude: 36.8712,
    elevationM: 1680,
    coordinates: { x: 400, y: 300 },
    state: 'NORMAL',
    telemetry: {
      activePowerMW: { value: 650, unit: 'MW', timestamp: new Date().toISOString(), source: 'SCADA_EMS', quality: 'GOOD', freshness: 'LIVE', confidence: 99 },
      reactivePowerMVAR: { value: 92, unit: 'MVAR', timestamp: new Date().toISOString(), source: 'SCADA_EMS', quality: 'GOOD', freshness: 'LIVE', confidence: 98 },
      voltageKV: { value: 401.5, unit: 'kV', timestamp: new Date().toISOString(), source: 'WAMS_PMU', quality: 'GOOD', freshness: 'LIVE', confidence: 99.6 },
      frequencyHz: { value: 50.00, unit: 'Hz', timestamp: new Date().toISOString(), source: 'WAMS_PMU', quality: 'GOOD', freshness: 'LIVE', confidence: 99.9 },
      thermalLoadingPct: { value: 69.5, unit: '%', timestamp: new Date().toISOString(), source: 'SCADA_EMS', quality: 'GOOD', freshness: 'LIVE', confidence: 98 },
      transformerOilTempC: { value: 58.4, unit: '°C', timestamp: new Date().toISOString(), source: 'SCADA_EMS', quality: 'GOOD', freshness: 'LIVE', confidence: 97 },
      sf6PressureBar: { value: 6.3, unit: 'bar', timestamp: new Date().toISOString(), source: 'SCADA_EMS', quality: 'GOOD', freshness: 'LIVE', confidence: 98 },
      powerFactor: { value: 0.98, unit: 'PF', timestamp: new Date().toISOString(), source: 'SCADA_EMS', quality: 'GOOD', freshness: 'LIVE', confidence: 99 }
    },
    ratedCapacityMVA: 950,
    currentLoadMW: 650,
    peakLoadMW: 780,
    healthScore: 89,
    riskScore: 28,
    criticalityScore: 9,
    nMinusOneRedundant: true,
    singlePointOfFailure: false,
    connectedLines: ['tl_ssw_nbn', 'tl_nbn_ring'],
    connectedSubstations: ['suswa', 'nairobi_ring'],
    downstreamNodes: ['nairobi_ring'],
    upstreamNodes: ['suswa'],
    alternativePaths: ['suswa -> isinya -> nairobi_ring'],
    transformersCount: 3,
    baysCount: 12,
    breakersCount: 20,
    protectionRelaysCount: 32,
    sources: ['SCADA_EMS', 'GIS_POSTGIS', 'WAMS_PMU'],
    lastUpdated: '1 sec ago',
    maintenanceForecast: 'Nairobi Ring 220kV feed load-balancing test scheduled.',
    activeProjects: ['Nairobi Metropolis 220kV Ring Reinforcement'],
    activeTenders: ['Underground 220kV XLPE Cable Accessories'],
    contractors: ['Larsen & Toubro Kenya', 'Prysmian Cables']
  },
  nairobi_ring: {
    id: 'nairobi_ring',
    name: 'Nairobi 220kV Ring (Embakasi / Dandora)',
    code: 'NBR-220-01',
    type: 'SUBSTATION',
    voltageLevelKV: 220,
    region: 'NAIROBI',
    county: 'Nairobi',
    scadaId: 'SCD-KTR-NBR-01',
    gisId: 'GIS-NODE-88435',
    eamId: 'EAM-SAP-EQ-10065',
    engineeringId: 'ENG-DWG-220-NBR-01',
    confidence: 96.5,
    reconciliationStatus: 'VERIFIED',
    latitude: -1.3125,
    longitude: 36.9102,
    elevationM: 1620,
    coordinates: { x: 420, y: 340 },
    state: 'CONGESTED',
    telemetry: {
      activePowerMW: { value: 820, unit: 'MW', timestamp: new Date().toISOString(), source: 'SCADA_EMS', quality: 'GOOD', freshness: 'LIVE', confidence: 98 },
      reactivePowerMVAR: { value: 140, unit: 'MVAR', timestamp: new Date().toISOString(), source: 'SCADA_EMS', quality: 'GOOD', freshness: 'LIVE', confidence: 96 },
      voltageKV: { value: 218.4, unit: 'kV', timestamp: new Date().toISOString(), source: 'WAMS_PMU', quality: 'GOOD', freshness: 'LIVE', confidence: 99.2 },
      frequencyHz: { value: 49.98, unit: 'Hz', timestamp: new Date().toISOString(), source: 'WAMS_PMU', quality: 'GOOD', freshness: 'LIVE', confidence: 99.9 },
      thermalLoadingPct: { value: 89.2, unit: '%', timestamp: new Date().toISOString(), source: 'SCADA_EMS', quality: 'GOOD', freshness: 'LIVE', confidence: 97 },
      transformerOilTempC: { value: 72.8, unit: '°C', timestamp: new Date().toISOString(), source: 'SCADA_EMS', quality: 'GOOD', freshness: 'LIVE', confidence: 95 },
      sf6PressureBar: { value: 6.1, unit: 'bar', timestamp: new Date().toISOString(), source: 'SCADA_EMS', quality: 'QUESTIONABLE', freshness: 'LIVE', confidence: 92 },
      powerFactor: { value: 0.95, unit: 'PF', timestamp: new Date().toISOString(), source: 'SCADA_EMS', quality: 'GOOD', freshness: 'LIVE', confidence: 98 }
    },
    ratedCapacityMVA: 920,
    currentLoadMW: 820,
    peakLoadMW: 890,
    healthScore: 71,
    riskScore: 74,
    criticalityScore: 9,
    nMinusOneRedundant: true,
    singlePointOfFailure: false,
    connectedLines: ['tl_nbn_ring', 'tl_isy_emb'],
    connectedSubstations: ['nairobi_north', 'isinya'],
    downstreamNodes: ['kplc_distribution_feeders'],
    upstreamNodes: ['nairobi_north', 'isinya'],
    alternativePaths: ['isinya -> embakasi direct 220kV line'],
    transformersCount: 4,
    baysCount: 16,
    breakersCount: 24,
    protectionRelaysCount: 40,
    sources: ['SCADA_EMS', 'GIS_POSTGIS', 'WAMS_PMU'],
    lastUpdated: '1 sec ago',
    maintenanceForecast: 'High thermal alarm on T1 winding. Forced-air cooling fans active.',
    activeProjects: ['Nairobi Metro Ring Capacity Expansion'],
    activeTenders: ['Auto-Transformer Cooling System Retrofit'],
    contractors: ['ABB Power Grids Kenya', 'PowerChina']
  },
  mariakani: {
    id: 'mariakani',
    name: 'Mariakani 400kV / 220kV Coastal Hub',
    code: 'MRK-400-01',
    type: 'SUBSTATION',
    voltageLevelKV: 400,
    region: 'COAST',
    county: 'Kilifi',
    scadaId: 'SCD-KTR-MRK-01',
    gisId: 'GIS-NODE-88450',
    eamId: 'EAM-SAP-EQ-10080',
    engineeringId: 'ENG-DWG-400-MRK-01',
    confidence: 97.4,
    reconciliationStatus: 'VERIFIED',
    latitude: -3.8643,
    longitude: 39.4678,
    elevationM: 190,
    coordinates: { x: 550, y: 550 },
    state: 'NORMAL',
    telemetry: {
      activePowerMW: { value: 580, unit: 'MW', timestamp: new Date().toISOString(), source: 'SCADA_EMS', quality: 'GOOD', freshness: 'LIVE', confidence: 99 },
      reactivePowerMVAR: { value: 75, unit: 'MVAR', timestamp: new Date().toISOString(), source: 'SCADA_EMS', quality: 'GOOD', freshness: 'LIVE', confidence: 98 },
      voltageKV: { value: 404.2, unit: 'kV', timestamp: new Date().toISOString(), source: 'WAMS_PMU', quality: 'GOOD', freshness: 'LIVE', confidence: 99.5 },
      frequencyHz: { value: 50.02, unit: 'Hz', timestamp: new Date().toISOString(), source: 'WAMS_PMU', quality: 'GOOD', freshness: 'LIVE', confidence: 99.9 },
      thermalLoadingPct: { value: 52.3, unit: '%', timestamp: new Date().toISOString(), source: 'SCADA_EMS', quality: 'GOOD', freshness: 'LIVE', confidence: 98 },
      transformerOilTempC: { value: 49.0, unit: '°C', timestamp: new Date().toISOString(), source: 'SCADA_EMS', quality: 'GOOD', freshness: 'LIVE', confidence: 98 },
      sf6PressureBar: { value: 6.4, unit: 'bar', timestamp: new Date().toISOString(), source: 'SCADA_EMS', quality: 'GOOD', freshness: 'LIVE', confidence: 99 },
      powerFactor: { value: 0.98, unit: 'PF', timestamp: new Date().toISOString(), source: 'SCADA_EMS', quality: 'GOOD', freshness: 'LIVE', confidence: 99 }
    },
    ratedCapacityMVA: 900,
    currentLoadMW: 580,
    peakLoadMW: 710,
    healthScore: 94,
    riskScore: 18,
    criticalityScore: 8,
    nMinusOneRedundant: true,
    singlePointOfFailure: false,
    connectedLines: ['tl_isy_mrk', 'tl_mrk_rbi', 'tl_mrk_grs'],
    connectedSubstations: ['isinya', 'rabai', 'garsen'],
    downstreamNodes: ['rabai', 'garsen'],
    upstreamNodes: ['isinya'],
    alternativePaths: ['mombasa-nairobi direct 400kV line 2'],
    transformersCount: 3,
    baysCount: 12,
    breakersCount: 18,
    protectionRelaysCount: 28,
    sources: ['SCADA_EMS', 'GIS_POSTGIS', 'WAMS_PMU'],
    lastUpdated: '1 sec ago',
    maintenanceForecast: 'Marine coastal salinity insulator washing protocol scheduled.',
    activeProjects: ['Mariakani-Diani 132kV Transmission Project'],
    activeTenders: ['RTV Silicon Coating for Coastal Insulators'],
    contractors: ['KEC International', 'National Contracting Co']
  },
  rabai: {
    id: 'rabai',
    name: 'Rabai 220kV / 132kV Substation',
    code: 'RBI-220-01',
    type: 'SUBSTATION',
    voltageLevelKV: 220,
    region: 'COAST',
    county: 'Kilifi',
    scadaId: 'SCD-KTR-RBI-01',
    gisId: 'GIS-NODE-88455',
    eamId: 'EAM-SAP-EQ-10085',
    engineeringId: 'ENG-DWG-220-RBI-01',
    confidence: 96.8,
    reconciliationStatus: 'VERIFIED',
    latitude: -3.9212,
    longitude: 39.5641,
    elevationM: 110,
    coordinates: { x: 580, y: 580 },
    state: 'NORMAL',
    telemetry: {
      activePowerMW: { value: 340, unit: 'MW', timestamp: new Date().toISOString(), source: 'SCADA_EMS', quality: 'GOOD', freshness: 'LIVE', confidence: 98 },
      reactivePowerMVAR: { value: 45, unit: 'MVAR', timestamp: new Date().toISOString(), source: 'SCADA_EMS', quality: 'GOOD', freshness: 'LIVE', confidence: 97 },
      voltageKV: { value: 221.0, unit: 'kV', timestamp: new Date().toISOString(), source: 'WAMS_PMU', quality: 'GOOD', freshness: 'LIVE', confidence: 99.4 },
      frequencyHz: { value: 50.01, unit: 'Hz', timestamp: new Date().toISOString(), source: 'WAMS_PMU', quality: 'GOOD', freshness: 'LIVE', confidence: 99.9 },
      thermalLoadingPct: { value: 48.6, unit: '%', timestamp: new Date().toISOString(), source: 'SCADA_EMS', quality: 'GOOD', freshness: 'LIVE', confidence: 98 },
      transformerOilTempC: { value: 46.5, unit: '°C', timestamp: new Date().toISOString(), source: 'SCADA_EMS', quality: 'GOOD', freshness: 'LIVE', confidence: 98 },
      sf6PressureBar: { value: 6.4, unit: 'bar', timestamp: new Date().toISOString(), source: 'SCADA_EMS', quality: 'GOOD', freshness: 'LIVE', confidence: 99 },
      powerFactor: { value: 0.98, unit: 'PF', timestamp: new Date().toISOString(), source: 'SCADA_EMS', quality: 'GOOD', freshness: 'LIVE', confidence: 99 }
    },
    ratedCapacityMVA: 650,
    currentLoadMW: 340,
    peakLoadMW: 420,
    healthScore: 95,
    riskScore: 16,
    criticalityScore: 7,
    nMinusOneRedundant: true,
    singlePointOfFailure: false,
    connectedLines: ['tl_mrk_rbi'],
    connectedSubstations: ['mariakani'],
    downstreamNodes: ['mombasa_island_port'],
    upstreamNodes: ['mariakani'],
    alternativePaths: ['mombasa port diesel peaking link'],
    transformersCount: 2,
    baysCount: 8,
    breakersCount: 14,
    protectionRelaysCount: 22,
    sources: ['SCADA_EMS', 'GIS_POSTGIS', 'WAMS_PMU'],
    lastUpdated: '2 sec ago',
    maintenanceForecast: 'Scheduled switchgear bay bus cleaning.',
    activeProjects: ['Mombasa Port 132kV Power Supply Reinforcement'],
    activeTenders: ['Mombasa Port Under-water Crossing Spares'],
    contractors: ['East African Cables', 'Siemens Kenya']
  },
  lessos: {
    id: 'lessos',
    name: 'Lessos 400kV / 220kV / 132kV Western Hub',
    code: 'LES-400-01',
    type: 'SUBSTATION',
    voltageLevelKV: 400,
    region: 'WESTERN',
    county: 'Nandi',
    scadaId: 'SCD-KTR-LES-01',
    gisId: 'GIS-NODE-88460',
    eamId: 'EAM-SAP-EQ-10090',
    engineeringId: 'ENG-DWG-400-LES-01',
    confidence: 98.1,
    reconciliationStatus: 'VERIFIED',
    latitude: 0.2104,
    longitude: 35.2941,
    elevationM: 2050,
    coordinates: { x: 180, y: 200 },
    state: 'NORMAL',
    telemetry: {
      activePowerMW: { value: 610, unit: 'MW', timestamp: new Date().toISOString(), source: 'SCADA_EMS', quality: 'GOOD', freshness: 'LIVE', confidence: 99 },
      reactivePowerMVAR: { value: 80, unit: 'MVAR', timestamp: new Date().toISOString(), source: 'SCADA_EMS', quality: 'GOOD', freshness: 'LIVE', confidence: 98 },
      voltageKV: { value: 401.8, unit: 'kV', timestamp: new Date().toISOString(), source: 'WAMS_PMU', quality: 'GOOD', freshness: 'LIVE', confidence: 99.6 },
      frequencyHz: { value: 50.01, unit: 'Hz', timestamp: new Date().toISOString(), source: 'WAMS_PMU', quality: 'GOOD', freshness: 'LIVE', confidence: 99.9 },
      thermalLoadingPct: { value: 61.2, unit: '%', timestamp: new Date().toISOString(), source: 'SCADA_EMS', quality: 'GOOD', freshness: 'LIVE', confidence: 98 },
      transformerOilTempC: { value: 53.8, unit: '°C', timestamp: new Date().toISOString(), source: 'SCADA_EMS', quality: 'GOOD', freshness: 'LIVE', confidence: 97 },
      sf6PressureBar: { value: 6.3, unit: 'bar', timestamp: new Date().toISOString(), source: 'SCADA_EMS', quality: 'GOOD', freshness: 'LIVE', confidence: 99 },
      powerFactor: { value: 0.98, unit: 'PF', timestamp: new Date().toISOString(), source: 'SCADA_EMS', quality: 'GOOD', freshness: 'LIVE', confidence: 99 }
    },
    ratedCapacityMVA: 950,
    currentLoadMW: 610,
    peakLoadMW: 730,
    healthScore: 91,
    riskScore: 24,
    criticalityScore: 9,
    nMinusOneRedundant: true,
    singlePointOfFailure: false,
    connectedLines: ['tl_olk_les', 'tl_les_ksm', 'tl_les_tororo', 'tl_trk_les'],
    connectedSubstations: ['olkaria', 'kisumu', 'tororo_uganda', 'turkwel'],
    downstreamNodes: ['kisumu', 'tororo_uganda', 'eldoret'],
    upstreamNodes: ['olkaria', 'turkwel'],
    alternativePaths: ['olkaria -> suswa -> isinya', 'turkwel -> lessos -> eldoret'],
    transformersCount: 4,
    baysCount: 14,
    breakersCount: 22,
    protectionRelaysCount: 36,
    sources: ['SCADA_EMS', 'GIS_POSTGIS', 'WAMS_PMU'],
    lastUpdated: '1 sec ago',
    maintenanceForecast: 'Uganda 400kV synchronizing check completed.',
    activeProjects: ['Lessos-Tororo 400kV Regional Interconnector'],
    activeTenders: ['Differential Protection Relay Retrofit'],
    contractors: ['Kalpataru Power Transmission', 'Efacec']
  },
  kisumu: {
    id: 'kisumu',
    name: 'Kisumu (Mamboleo) 220kV / 132kV Substation',
    code: 'KSM-220-01',
    type: 'SUBSTATION',
    voltageLevelKV: 220,
    region: 'WESTERN',
    county: 'Kisumu',
    scadaId: 'SCD-KTR-KSM-01',
    gisId: 'GIS-NODE-88465',
    eamId: 'EAM-SAP-EQ-10095',
    engineeringId: 'ENG-DWG-220-KSM-01',
    confidence: 97.2,
    reconciliationStatus: 'VERIFIED',
    latitude: -0.0712,
    longitude: 34.7812,
    elevationM: 1180,
    coordinates: { x: 120, y: 260 },
    state: 'NORMAL',
    telemetry: {
      activePowerMW: { value: 290, unit: 'MW', timestamp: new Date().toISOString(), source: 'SCADA_EMS', quality: 'GOOD', freshness: 'LIVE', confidence: 99 },
      reactivePowerMVAR: { value: 42, unit: 'MVAR', timestamp: new Date().toISOString(), source: 'SCADA_EMS', quality: 'GOOD', freshness: 'LIVE', confidence: 98 },
      voltageKV: { value: 220.4, unit: 'kV', timestamp: new Date().toISOString(), source: 'WAMS_PMU', quality: 'GOOD', freshness: 'LIVE', confidence: 99.5 },
      frequencyHz: { value: 50.00, unit: 'Hz', timestamp: new Date().toISOString(), source: 'WAMS_PMU', quality: 'GOOD', freshness: 'LIVE', confidence: 99.9 },
      thermalLoadingPct: { value: 54.0, unit: '%', timestamp: new Date().toISOString(), source: 'SCADA_EMS', quality: 'GOOD', freshness: 'LIVE', confidence: 98 },
      transformerOilTempC: { value: 50.1, unit: '°C', timestamp: new Date().toISOString(), source: 'SCADA_EMS', quality: 'GOOD', freshness: 'LIVE', confidence: 97 },
      sf6PressureBar: { value: 6.4, unit: 'bar', timestamp: new Date().toISOString(), source: 'SCADA_EMS', quality: 'GOOD', freshness: 'LIVE', confidence: 99 },
      powerFactor: { value: 0.98, unit: 'PF', timestamp: new Date().toISOString(), source: 'SCADA_EMS', quality: 'GOOD', freshness: 'LIVE', confidence: 99 }
    },
    ratedCapacityMVA: 500,
    currentLoadMW: 290,
    peakLoadMW: 360,
    healthScore: 93,
    riskScore: 20,
    criticalityScore: 7,
    nMinusOneRedundant: true,
    singlePointOfFailure: false,
    connectedLines: ['tl_les_ksm', 'tl_snd_ksm'],
    connectedSubstations: ['lessos', 'sondu_miriu'],
    downstreamNodes: ['western_sugar_belt_grid'],
    upstreamNodes: ['lessos', 'sondu_miriu'],
    alternativePaths: ['sondu miriu 132kV direct feed'],
    transformersCount: 2,
    baysCount: 8,
    breakersCount: 14,
    protectionRelaysCount: 24,
    sources: ['SCADA_EMS', 'GIS_POSTGIS', 'WAMS_PMU'],
    lastUpdated: '2 sec ago',
    maintenanceForecast: 'Lake Basin industrial feeder breaker test planned.',
    activeProjects: ['Olkaria-Lessos-Kisumu 220kV Reinforcement'],
    activeTenders: ['132kV SF6 Gas Analyzers and Top-up units'],
    contractors: ['NARI Group Corp', 'KEC International']
  },
  loiyangalani: {
    id: 'loiyangalani',
    name: 'Loiyangalani 400kV Wind Grid Substation',
    code: 'LOY-400-01',
    type: 'GENERATOR_INTERFACE',
    voltageLevelKV: 400,
    region: 'NORTH_EASTERN',
    county: 'Marsabit',
    scadaId: 'SCD-KTR-LOY-01',
    gisId: 'GIS-NODE-88480',
    eamId: 'EAM-SAP-EQ-10110',
    engineeringId: 'ENG-DWG-400-LOY-01',
    confidence: 96.1,
    reconciliationStatus: 'VERIFIED',
    latitude: 2.7481,
    longitude: 36.7123,
    elevationM: 420,
    coordinates: { x: 340, y: 70 },
    state: 'NORMAL',
    telemetry: {
      activePowerMW: { value: 310, unit: 'MW', timestamp: new Date().toISOString(), source: 'SCADA_EMS', quality: 'GOOD', freshness: 'LIVE', confidence: 98 },
      reactivePowerMVAR: { value: 35, unit: 'MVAR', timestamp: new Date().toISOString(), source: 'SCADA_EMS', quality: 'GOOD', freshness: 'LIVE', confidence: 97 },
      voltageKV: { value: 403.0, unit: 'kV', timestamp: new Date().toISOString(), source: 'WAMS_PMU', quality: 'GOOD', freshness: 'LIVE', confidence: 99.4 },
      frequencyHz: { value: 50.02, unit: 'Hz', timestamp: new Date().toISOString(), source: 'WAMS_PMU', quality: 'GOOD', freshness: 'LIVE', confidence: 99.9 },
      thermalLoadingPct: { value: 72.5, unit: '%', timestamp: new Date().toISOString(), source: 'SCADA_EMS', quality: 'GOOD', freshness: 'LIVE', confidence: 98 },
      transformerOilTempC: { value: 62.0, unit: '°C', timestamp: new Date().toISOString(), source: 'SCADA_EMS', quality: 'GOOD', freshness: 'LIVE', confidence: 96 },
      sf6PressureBar: { value: 6.2, unit: 'bar', timestamp: new Date().toISOString(), source: 'SCADA_EMS', quality: 'GOOD', freshness: 'LIVE', confidence: 98 },
      powerFactor: { value: 0.99, unit: 'PF', timestamp: new Date().toISOString(), source: 'SCADA_EMS', quality: 'GOOD', freshness: 'LIVE', confidence: 99 }
    },
    ratedCapacityMVA: 450,
    currentLoadMW: 310,
    peakLoadMW: 310,
    healthScore: 88,
    riskScore: 36,
    criticalityScore: 8,
    nMinusOneRedundant: false,
    singlePointOfFailure: true,
    connectedLines: ['tl_loy_ssw'],
    connectedSubstations: ['suswa'],
    downstreamNodes: ['suswa'],
    upstreamNodes: ['lake_turkana_wind_power'],
    alternativePaths: ['none (radial 400kV backbone to Suswa)'],
    transformersCount: 2,
    baysCount: 6,
    breakersCount: 10,
    protectionRelaysCount: 18,
    sources: ['SCADA_EMS', 'GIS_POSTGIS', 'WAMS_PMU'],
    lastUpdated: '1 sec ago',
    maintenanceForecast: 'Desert dust air filter purge scheduled every 14 days.',
    activeProjects: ['Lake Turkana Wind Power Transmission Line Stabilization'],
    activeTenders: ['Desert Solar and Wind Ingress Filters'],
    contractors: ['Siemens Gamesa', 'Isolux Corsan']
  },
  moyale_hvdc: {
    id: 'moyale_hvdc',
    name: 'Ethiopia-Kenya 500kV HVDC Converter Station',
    code: 'ETH-500-01',
    type: 'HVDC_CONVERTER',
    voltageLevelKV: 500,
    region: 'NORTH_EASTERN',
    county: 'Marsabit',
    scadaId: 'SCD-KTR-ETH-01',
    gisId: 'GIS-NODE-88490',
    eamId: 'EAM-SAP-EQ-10120',
    engineeringId: 'ENG-DWG-500-ETH-HVDC',
    confidence: 99.0,
    reconciliationStatus: 'VERIFIED',
    latitude: 3.5124,
    longitude: 39.0543,
    elevationM: 980,
    coordinates: { x: 500, y: 40 },
    state: 'NORMAL',
    telemetry: {
      activePowerMW: { value: 750, unit: 'MW', timestamp: new Date().toISOString(), source: 'SCADA_EMS', quality: 'GOOD', freshness: 'LIVE', confidence: 99 },
      reactivePowerMVAR: { value: 0, unit: 'MVAR', timestamp: new Date().toISOString(), source: 'SCADA_EMS', quality: 'GOOD', freshness: 'LIVE', confidence: 99 },
      voltageKV: { value: 500.0, unit: 'kV', timestamp: new Date().toISOString(), source: 'WAMS_PMU', quality: 'GOOD', freshness: 'LIVE', confidence: 99.8 },
      frequencyHz: { value: 50.00, unit: 'Hz', timestamp: new Date().toISOString(), source: 'WAMS_PMU', quality: 'GOOD', freshness: 'LIVE', confidence: 99.9 },
      thermalLoadingPct: { value: 37.5, unit: '%', timestamp: new Date().toISOString(), source: 'SCADA_EMS', quality: 'GOOD', freshness: 'LIVE', confidence: 99 },
      transformerOilTempC: { value: 48.0, unit: '°C', timestamp: new Date().toISOString(), source: 'SCADA_EMS', quality: 'GOOD', freshness: 'LIVE', confidence: 98 },
      sf6PressureBar: { value: 6.5, unit: 'bar', timestamp: new Date().toISOString(), source: 'SCADA_EMS', quality: 'GOOD', freshness: 'LIVE', confidence: 99 },
      powerFactor: { value: 1.00, unit: 'PF', timestamp: new Date().toISOString(), source: 'SCADA_EMS', quality: 'GOOD', freshness: 'LIVE', confidence: 99.9 }
    },
    ratedCapacityMVA: 2000,
    currentLoadMW: 750,
    peakLoadMW: 1200,
    healthScore: 98,
    riskScore: 12,
    criticalityScore: 10,
    nMinusOneRedundant: true,
    singlePointOfFailure: false,
    connectedLines: ['tl_hvdc_eth_ken'],
    connectedSubstations: ['suswa'],
    downstreamNodes: ['suswa'],
    upstreamNodes: ['wolayta_sodo_ethiopia'],
    alternativePaths: ['bi-pole mode fallback to mono-pole ground return'],
    transformersCount: 6,
    baysCount: 8,
    breakersCount: 16,
    protectionRelaysCount: 48,
    sources: ['SCADA_EMS', 'GIS_POSTGIS', 'WAMS_PMU', 'EAM_SAP'],
    lastUpdated: '1 sec ago',
    maintenanceForecast: 'HVDC Thyristor valve cooling coolant conductivity audit.',
    activeProjects: ['Eastern Electricity Highway Project (500kV HVDC)'],
    activeTenders: ['HVDC Converter Valve Spares & Diagnostic Unit'],
    contractors: ['Hitachi Energy', 'China Electric Power Equipment Corp']
  }
};

// Canonical Transmission Lines
export const CANONICAL_LINES: Record<string, TransmissionLine> = {
  tl_ssw_olk: {
    id: 'tl_ssw_olk',
    code: 'TL-400-SSW-OLK-01',
    name: 'Suswa - Olkaria 400kV Double Circuit',
    fromSubstationId: 'olkaria',
    toSubstationId: 'suswa',
    voltageKV: 400,
    lengthKM: 45,
    conductorType: 'Quad AAAC Zebra',
    thermalRatingMVA: 1400,
    currentLoadMW: 890,
    loadingPct: 63.5,
    state: 'NORMAL',
    pathCoordinates: [[36.3012, -0.8842], [36.3532, -1.0543]],
    nMinusOneRisk: false,
    activeAlarmsCount: 0,
    powerFlowDirection: 'FORWARD'
  },
  tl_ssw_isy: {
    id: 'tl_ssw_isy',
    code: 'TL-400-SSW-ISN-01',
    name: 'Suswa - Isinya 400kV Bulk Corridor',
    fromSubstationId: 'suswa',
    toSubstationId: 'isinya',
    voltageKV: 400,
    lengthKM: 102,
    conductorType: 'Quad ACSR Bersimis',
    thermalRatingMVA: 1600,
    currentLoadMW: 1120,
    loadingPct: 70.0,
    state: 'NORMAL',
    pathCoordinates: [[36.3532, -1.0543], [36.8543, -1.6721]],
    nMinusOneRisk: false,
    activeAlarmsCount: 1,
    powerFlowDirection: 'FORWARD'
  },
  tl_ssw_nbn: {
    id: 'tl_ssw_nbn',
    code: 'TL-400-SSW-NBN-01',
    name: 'Suswa - Nairobi North 400kV Trunk',
    fromSubstationId: 'suswa',
    toSubstationId: 'nairobi_north',
    voltageKV: 400,
    lengthKM: 68,
    conductorType: 'Quad ACSR Moose',
    thermalRatingMVA: 1200,
    currentLoadMW: 650,
    loadingPct: 54.1,
    state: 'NORMAL',
    pathCoordinates: [[36.3532, -1.0543], [36.8712, -1.1894]],
    nMinusOneRisk: false,
    activeAlarmsCount: 0,
    powerFlowDirection: 'FORWARD'
  },
  tl_isy_mrk: {
    id: 'tl_isy_mrk',
    code: 'TL-400-ISN-MRK-01',
    name: 'Mombasa - Nairobi 400kV Line 1 (Isinya - Mariakani)',
    fromSubstationId: 'isinya',
    toSubstationId: 'mariakani',
    voltageKV: 400,
    lengthKM: 440,
    conductorType: 'Triple AAAC Zebra',
    thermalRatingMVA: 1200,
    currentLoadMW: 580,
    loadingPct: 48.3,
    state: 'NORMAL',
    pathCoordinates: [[36.8543, -1.6721], [39.4678, -3.8643]],
    nMinusOneRisk: false,
    activeAlarmsCount: 0,
    powerFlowDirection: 'FORWARD'
  },
  tl_mrk_rbi: {
    id: 'tl_mrk_rbi',
    code: 'TL-220-MRK-RBI-01',
    name: 'Mariakani - Rabai 220kV Interconnector',
    fromSubstationId: 'mariakani',
    toSubstationId: 'rabai',
    voltageKV: 220,
    lengthKM: 28,
    conductorType: 'Twin ACSR Moose',
    thermalRatingMVA: 650,
    currentLoadMW: 340,
    loadingPct: 52.3,
    state: 'NORMAL',
    pathCoordinates: [[39.4678, -3.8643], [39.5641, -3.9212]],
    nMinusOneRisk: false,
    activeAlarmsCount: 0,
    powerFlowDirection: 'FORWARD'
  },
  tl_olk_les: {
    id: 'tl_olk_les',
    code: 'TL-400-OLK-LES-01',
    name: 'Olkaria - Lessos 400kV Western Spine',
    fromSubstationId: 'olkaria',
    toSubstationId: 'lessos',
    voltageKV: 400,
    lengthKM: 215,
    conductorType: 'Twin ACSR Curlew',
    thermalRatingMVA: 1200,
    currentLoadMW: 610,
    loadingPct: 50.8,
    state: 'NORMAL',
    pathCoordinates: [[36.3012, -0.8842], [35.2941, 0.2104]],
    nMinusOneRisk: false,
    activeAlarmsCount: 0,
    powerFlowDirection: 'FORWARD'
  },
  tl_les_ksm: {
    id: 'tl_les_ksm',
    code: 'TL-220-LES-KSM-01',
    name: 'Lessos - Kisumu (Mamboleo) 220kV Line',
    fromSubstationId: 'lessos',
    toSubstationId: 'kisumu',
    voltageKV: 220,
    lengthKM: 78,
    conductorType: 'Twin ACSR Zebra',
    thermalRatingMVA: 500,
    currentLoadMW: 290,
    loadingPct: 58.0,
    state: 'NORMAL',
    pathCoordinates: [[35.2941, 0.2104], [34.7812, -0.0712]],
    nMinusOneRisk: false,
    activeAlarmsCount: 0,
    powerFlowDirection: 'FORWARD'
  },
  tl_loy_ssw: {
    id: 'tl_loy_ssw',
    code: 'TL-400-LOY-SSW-01',
    name: 'Loiyangalani - Suswa 400kV Wind Transmission Line',
    fromSubstationId: 'loiyangalani',
    toSubstationId: 'suswa',
    voltageKV: 400,
    lengthKM: 435,
    conductorType: 'Triple ACSR Bersimis',
    thermalRatingMVA: 1200,
    currentLoadMW: 310,
    loadingPct: 25.8,
    state: 'NORMAL',
    pathCoordinates: [[36.7123, 2.7481], [36.3532, -1.0543]],
    nMinusOneRisk: true,
    activeAlarmsCount: 0,
    powerFlowDirection: 'FORWARD'
  },
  tl_hvdc_eth_ken: {
    id: 'tl_hvdc_eth_ken',
    code: 'TL-500-HVDC-ETH-KEN',
    name: 'Ethiopia - Kenya 500kV HVDC Bipole Corridor',
    fromSubstationId: 'moyale_hvdc',
    toSubstationId: 'suswa',
    voltageKV: 500,
    lengthKM: 612,
    conductorType: 'Quad Bersimis HVDC Bipole',
    thermalRatingMVA: 2000,
    currentLoadMW: 750,
    loadingPct: 37.5,
    state: 'NORMAL',
    pathCoordinates: [[39.0543, 3.5124], [36.3532, -1.0543]],
    nMinusOneRisk: false,
    activeAlarmsCount: 0,
    powerFlowDirection: 'FORWARD'
  },
  tl_nbn_ring: {
    id: 'tl_nbn_ring',
    code: 'TL-220-NBN-NBR-01',
    name: 'Nairobi North - Nairobi Ring 220kV Feed',
    fromSubstationId: 'nairobi_north',
    toSubstationId: 'nairobi_ring',
    voltageKV: 220,
    lengthKM: 24,
    conductorType: 'Twin ACSR Moose',
    thermalRatingMVA: 650,
    currentLoadMW: 480,
    loadingPct: 73.8,
    state: 'WARNING',
    pathCoordinates: [[36.8712, -1.1894], [36.9102, -1.3125]],
    nMinusOneRisk: true,
    activeAlarmsCount: 1,
    powerFlowDirection: 'FORWARD'
  },
  tl_isy_emb: {
    id: 'tl_isy_emb',
    code: 'TL-220-ISN-EMB-01',
    name: 'Isinya - Embakasi 220kV Supply Line',
    fromSubstationId: 'isinya',
    toSubstationId: 'nairobi_ring',
    voltageKV: 220,
    lengthKM: 42,
    conductorType: 'Twin ACSR Zebra',
    thermalRatingMVA: 650,
    currentLoadMW: 340,
    loadingPct: 52.3,
    state: 'NORMAL',
    pathCoordinates: [[36.8543, -1.6721], [36.9102, -1.3125]],
    nMinusOneRisk: false,
    activeAlarmsCount: 0,
    powerFlowDirection: 'FORWARD'
  }
};

// 10 Authoritative KPI Families
export const CANONICAL_KPIS: KpiFamily[] = [
  {
    id: '01_system_demand',
    label: '01 SYSTEM DEMAND',
    value: 2481,
    unit: 'MW',
    trend: 'UP',
    trendValue: '+3.7%',
    status: 'NORMAL',
    sparkline: [2150, 2210, 2280, 2340, 2390, 2430, 2465, 2481],
    secondaryMetric: { label: 'PEAK', value: 2932, unit: 'MW' },
    tertiaryMetric: { label: 'FORECAST', value: 2550, unit: 'MW' },
    freshnessSec: 2
  },
  {
    id: '02_generation_avail',
    label: '02 GENERATION AVAILABILITY',
    value: 3120,
    unit: 'MW',
    trend: 'STABLE',
    trendValue: '96.2%',
    status: 'OPTIMAL',
    sparkline: [3080, 3100, 3100, 3110, 3120, 3120, 3120, 3120],
    secondaryMetric: { label: 'COMMITTED', value: 2481, unit: 'MW' },
    tertiaryMetric: { label: 'SPINNING RES.', value: 639, unit: 'MW' },
    freshnessSec: 2
  },
  {
    id: '03_frequency',
    label: '03 GRID FREQUENCY',
    value: '50.02',
    unit: 'Hz',
    trend: 'STABLE',
    trendValue: '+0.02 Hz',
    status: 'OPTIMAL',
    sparkline: [50.01, 50.03, 50.02, 49.99, 50.01, 50.02, 50.01, 50.02],
    secondaryMetric: { label: 'DEV LIMIT', value: '±0.20', unit: 'Hz' },
    tertiaryMetric: { label: 'EXCURSIONS', value: 0, unit: '24h' },
    freshnessSec: 1
  },
  {
    id: '04_transmission_avail',
    label: '04 TRANSMISSION AVAILABILITY',
    value: '99.41',
    unit: '%',
    trend: 'STABLE',
    trendValue: 'Target 99.0%',
    status: 'OPTIMAL',
    sparkline: [99.2, 99.3, 99.4, 99.35, 99.4, 99.42, 99.41, 99.41],
    secondaryMetric: { label: 'ONLINE LINES', value: '38/39', unit: '' },
    tertiaryMetric: { label: 'OUTAGE CIR.', value: '1', unit: 'ckt' },
    freshnessSec: 3
  },
  {
    id: '05_substation_avail',
    label: '05 SUBSTATION STATUS',
    value: '48 / 49',
    unit: 'ONLINE',
    trend: 'STABLE',
    trendValue: '97.9%',
    status: 'NORMAL',
    sparkline: [48, 48, 48, 48, 48, 48, 48, 48],
    secondaryMetric: { label: 'DEGRADED', value: 1, unit: 'sub' },
    tertiaryMetric: { label: 'MAINTENANCE', value: 0, unit: '' },
    freshnessSec: 2
  },
  {
    id: '06_transformer_loading',
    label: '06 TRANSFORMER LOADING',
    value: '67.4',
    unit: '% AVG',
    trend: 'UP',
    trendValue: 'High 89.2%',
    status: 'NORMAL',
    sparkline: [58, 60, 62, 64, 65, 66, 67, 67.4],
    secondaryMetric: { label: 'CRITICAL (>85%)', value: 2, unit: 'banks' },
    tertiaryMetric: { label: 'HEADROOM', value: '32.6%', unit: '' },
    freshnessSec: 2
  },
  {
    id: '07_congestion',
    label: '07 TRANSMISSION CONGESTION',
    value: 'NORMAL',
    unit: '',
    trend: 'STABLE',
    trendValue: '1 Warning',
    status: 'NORMAL',
    sparkline: [1, 1, 2, 1, 1, 2, 1, 1],
    secondaryMetric: { label: 'WARNING CORR.', value: 'Nairobi Ring', unit: '' },
    tertiaryMetric: { label: 'THERMAL CAP.', value: 'Nominal', unit: '' },
    freshnessSec: 4
  },
  {
    id: '08_critical_alarms',
    label: '08 ACTIVE ALARMS',
    value: 3,
    unit: 'ACTIVE',
    trend: 'DOWN',
    trendValue: '0 P1 Critical',
    status: 'WARNING',
    sparkline: [5, 4, 4, 3, 4, 3, 3, 3],
    secondaryMetric: { label: 'P2 HIGH', value: 2, unit: '' },
    tertiaryMetric: { label: 'P3 MEDIUM', value: 1, unit: '' },
    freshnessSec: 1
  },
  {
    id: '09_asset_health',
    label: '09 ASSET HEALTH INDEX',
    value: '91.8',
    unit: '/ 100',
    trend: 'STABLE',
    trendValue: 'Watch 2',
    status: 'OPTIMAL',
    sparkline: [91.2, 91.5, 91.6, 91.7, 91.8, 91.8, 91.8, 91.8],
    secondaryMetric: { label: 'HEALTHY', value: '94%', unit: '' },
    tertiaryMetric: { label: 'DEGRADED', value: '6%', unit: '' },
    freshnessSec: 5
  },
  {
    id: '10_grid_resilience',
    label: '10 GRID RESILIENCE SCORE',
    value: '94.6',
    unit: '/ 100',
    trend: 'STABLE',
    trendValue: 'N-1 Secure',
    status: 'OPTIMAL',
    sparkline: [93.8, 94.0, 94.2, 94.4, 94.5, 94.6, 94.6, 94.6],
    secondaryMetric: { label: 'SPOF EXPOSURE', value: 'Low (1 Node)', unit: '' },
    tertiaryMetric: { label: 'REDUNDANCY', value: '98.2%', unit: '' },
    freshnessSec: 3
  }
];

// Active Alarms Fabric
export const CANONICAL_ALARMS: GridAlarm[] = [
  {
    id: 'ALM-2026-0881',
    assetId: 'nairobi_ring',
    assetName: 'Nairobi 220kV Ring (Embakasi / Dandora)',
    code: 'ALM-THRM-TR1-HI',
    title: 'Transformer T1 Winding Temperature High (72.8°C)',
    category: 'THERMAL',
    severity: 'P2',
    state: 'ACTIVE',
    timestamp: '18:14:22 EAT',
    durationMin: 18,
    description: 'Auto-Transformer 220/66kV Bank 1 winding temperature exceeded Stage-1 alarm threshold (70°C). Auxiliary forced-air fan bank Stage 2 auto-engaged.',
    rootCauseAnalysis: 'Sustained peak evening industrial and domestic demand load concentration on the eastern metro ring corridor.',
    remedialAction: 'Shift 45MW load to Isinya 220kV feed via automated EMS tap changer coordination.',
    affectedEquipments: ['Transformer T1 (220/66kV 150MVA)', 'Bay B-04 Cooler Fan Bank'],
    source: 'SCADA_EMS'
  },
  {
    id: 'ALM-2026-0879',
    assetId: 'suswa',
    assetName: 'Suswa 500kV / 400kV EHV Hub',
    code: 'ALM-VOLT-SSW-500-L2',
    title: '500kV Busbar Phase-B Transient Voltage Harmonic Spike',
    category: 'VOLTAGE',
    severity: 'P2',
    state: 'ACTIVE',
    timestamp: '18:02:11 EAT',
    durationMin: 30,
    description: 'PMU detected 1.2% total harmonic distortion (THD) on Phase B during HVDC bi-pole power step adjustment from 650MW to 750MW.',
    rootCauseAnalysis: 'HVDC harmonic filter bank C switching transient damping resonance.',
    remedialAction: 'Filter bank tuning verified within permissible IEEE 519 boundary.',
    affectedEquipments: ['500kV Main Busbar Phase B', 'WAMS PMU-SSW-01'],
    source: 'WAMS_PMU'
  },
  {
    id: 'ALM-2026-0875',
    assetId: 'nairobi_ring',
    assetName: 'Nairobi 220kV Ring (Embakasi / Dandora)',
    code: 'ALM-SF6-NBR-B08',
    title: 'SF6 Gas Pressure Slow Drop Alert (6.1 bar)',
    category: 'SF6_GAS',
    severity: 'P3',
    state: 'ACTIVE',
    timestamp: '17:45:00 EAT',
    durationMin: 47,
    description: 'Gas density relay reading 6.1 bar (nominal 6.5 bar). Trip interlock threshold is 5.2 bar.',
    rootCauseAnalysis: 'Micro-gasket degradation on bay B-08 breaker valve joint.',
    remedialAction: 'Field maintenance work order WO-8841 auto-dispatched to Nairobi South transmission team.',
    affectedEquipments: ['220kV SF6 Breaker CB-220-08'],
    source: 'SCADA_EMS'
  }
];

// Bottom Event Fabric Stream
export const CANONICAL_EVENTS: GridEvent[] = [
  {
    id: 'EVT-9001',
    timestamp: '18:21:04 EAT',
    category: 'TELEMETRY',
    severity: 'INFO',
    assetId: 'suswa',
    assetName: 'Suswa Substation',
    title: 'HVDC Bipole Flow Ingest Synchronized',
    description: 'Ethiopia-Kenya 500kV HVDC power flow stabilized at 750.0 MW with zero reactive power penalty.',
    source: 'SCADA_EMS'
  },
  {
    id: 'EVT-9000',
    timestamp: '18:20:12 EAT',
    category: 'DISPATCH',
    severity: 'INFO',
    assetId: 'olkaria',
    assetName: 'Olkaria Geothermal',
    title: 'Baseload Generation Dispatch AGC Confirmed',
    description: 'National Control Centre confirmed 892 MW active injection into Suswa & Lessos 400kV corridors.',
    source: 'SCADA_EMS'
  },
  {
    id: 'EVT-8998',
    timestamp: '18:18:45 EAT',
    category: 'SYSTEM',
    severity: 'INFO',
    assetId: 'nairobi_north',
    assetName: 'Nairobi North 400kV',
    title: 'WAMS Phasor Measurement Telemetry Live Sync',
    description: 'Phasor angle delta between Suswa and Nairobi North is +4.2° (nominal stable range <15°).',
    source: 'WAMS_PMU'
  },
  {
    id: 'EVT-8995',
    timestamp: '18:14:22 EAT',
    category: 'ALARM',
    severity: 'HIGH',
    assetId: 'nairobi_ring',
    assetName: 'Nairobi 220kV Ring',
    title: 'P2 Alarm Raised: Transformer T1 Winding Temperature',
    description: 'Reading 72.8°C against Stage-1 70°C ceiling. Fan bank 2 auto-engaged.',
    correlationId: 'ALM-2026-0881',
    source: 'SCADA_EMS'
  },
  {
    id: 'EVT-8990',
    timestamp: '18:09:30 EAT',
    category: 'BREAKER',
    severity: 'INFO',
    assetId: 'lessos',
    assetName: 'Lessos 400kV Hub',
    title: 'Interconnector Breaker Closed & Synchronized',
    description: 'Tororo-Lessos 400kV regional tie line breaker synchro-check routine passed with 0.01 Hz frequency differential.',
    source: 'SCADA_EMS'
  },
  {
    id: 'EVT-8982',
    timestamp: '18:02:11 EAT',
    category: 'ALARM',
    severity: 'HIGH',
    assetId: 'suswa',
    assetName: 'Suswa 500kV Hub',
    title: 'P2 Alarm Raised: 500kV Phase-B Voltage Harmonic Spike',
    description: 'Total Harmonic Distortion detected at 1.2% during HVDC power ramping.',
    correlationId: 'ALM-2026-0879',
    source: 'WAMS_PMU'
  },
  {
    id: 'EVT-8975',
    timestamp: '17:55:00 EAT',
    category: 'PROTECTION',
    severity: 'INFO',
    assetId: 'mariakani',
    assetName: 'Mariakani 400kV',
    title: 'Line Differential Relay Health Check Passed',
    description: 'Main 1 (Optical RED670) and Main 2 (Distance REL670) protection relays reported 100% channel integrity.',
    source: 'SCADA_EMS'
  }
];

// Grounded AI Investigation Insights for each asset
export const CANONICAL_AI_INSIGHTS: Record<string, AiInvestigationInsight> = {
  suswa: {
    assetId: 'suswa',
    assetName: 'Suswa 500kV / 400kV EHV Hub',
    riskScore: 68,
    confidenceScore: 97.4,
    timestamp: '18:21:00 EAT',
    summary: 'Suswa operates as the primary national power routing nexus with 1,145 MW throughput (81.4% capacity). Risk is elevated due to simultaneous high loading and the 500kV harmonic transient during HVDC ramping.',
    riskDrivers: [
      { factor: 'Corridor Thermal Throughput', impactPct: 45, currentValue: '1,145 MW (81.4%)', severity: 'HIGH' },
      { factor: 'HVDC Bipole Power Ramp Transient', impactPct: 30, currentValue: '750 MW Ingest', severity: 'MEDIUM' },
      { factor: 'Auto-Transformer T2 Oil Maintenance Window', impactPct: 25, currentValue: 'Due in 6 Days', severity: 'LOW' }
    ],
    mitigations: [
      'Maintain Isinya 400kV bypass tie lines in hot standby state.',
      'Coordinate with NCC dispatch to throttle Nairobi North direct trunk if load surpasses 1,250 MW.',
      'Execute transformer T2 dissolved gas filtration on scheduled 6-day window.'
    ],
    projectedTrajectory: 'Evening peak load is projected to plateau at 1,180 MW by 19:30 EAT before declining to 820 MW by 22:00 EAT.',
    sourcesGrounded: ['SCADA_EMS (Real-time Tag: SSW_MW_TOT)', 'WAMS_PMU (Harmonic Spectrum)', 'EAM_SAP (WO-9912 Maintenance)']
  },
  nairobi_ring: {
    assetId: 'nairobi_ring',
    assetName: 'Nairobi 220kV Ring (Embakasi / Dandora)',
    riskScore: 74,
    confidenceScore: 96.0,
    timestamp: '18:21:00 EAT',
    summary: 'Nairobi Ring is currently congested at 89.2% transformer loading with active T1 winding temperature alert (72.8°C). Auxiliary cooling fans are actively stabilizing thermal gradient.',
    riskDrivers: [
      { factor: 'Transformer Winding Temperature', impactPct: 50, currentValue: '72.8°C (Alarm P2)', severity: 'HIGH' },
      { factor: 'Metro Feeder Demand Concentration', impactPct: 35, currentValue: '820 MW / 920 MVA', severity: 'HIGH' },
      { factor: 'SF6 Breaker CB-08 Micro-leak', impactPct: 15, currentValue: '6.1 bar (Watch)', severity: 'MEDIUM' }
    ],
    mitigations: [
      'Automated dispatch transfer of 45MW to Isinya 220kV feeder.',
      'Maintain continuous forced-air cooling fan stage 2 on Transformer Bank 1.',
      'Field crew dispatched for SF6 top-up (WO-8841).'
    ],
    projectedTrajectory: 'Thermal cooling will stabilize winding temp at ~70.5°C within 25 minutes once load transfers to Isinya.',
    sourcesGrounded: ['SCADA_EMS (Tag: NBR_TR1_TEMP)', 'EAM_SAP (Work Order WO-8841)', 'WAMS_PMU (Frequency 49.98 Hz)']
  },
  loiyangalani: {
    assetId: 'loiyangalani',
    assetName: 'Loiyangalani 400kV Wind Grid Substation',
    riskScore: 36,
    confidenceScore: 98.2,
    timestamp: '18:21:00 EAT',
    summary: 'Loiyangalani is operating cleanly at 310 MW wind generation. Single point of failure exposure exists on the 435km radial line to Suswa, requiring strict insulator wash vigilance.',
    riskDrivers: [
      { factor: 'Radial Line Single Point of Failure', impactPct: 60, currentValue: '435km Single Corridor', severity: 'MEDIUM' },
      { factor: 'Desert Dust Insulator Contamination', impactPct: 40, currentValue: '14-Day Cycle Active', severity: 'LOW' }
    ],
    mitigations: [
      'Maintain auto-reclose protection settings for lightning surge resilience on corridor towers.',
      'Preserve wind turbine curtailment ramping curves at Suswa interconnection.'
    ],
    projectedTrajectory: 'Wind generation output steady at 300-310 MW across next 6 hours according to Kenya Meteorological Department wind models.',
    sourcesGrounded: ['SCADA_EMS (Tag: LOY_GEN_MW)', 'WEATHER_MET (Marsabit Wind Vectors)', 'GIS_POSTGIS (Tower Span 1-1120)']
  }
};

for (const asset of Object.values(CANONICAL_SUBSTATIONS)) {
  annotateReferenceTelemetry(asset);
}
