import {
  SubstationEntity,
  TransmissionLineEntity,
  CircuitEntity,
  TransformerEntity,
  BreakerEntity,
  BusEntity,
  BayEntity,
  ProtectionRelayEntity,
  GenerationEntity,
  LoadEntity,
  CorridorEntity
} from '../types';

// ============================================================================
// CANONICAL CORRIDORS DATASET
// ============================================================================
export const CANONICAL_CORRIDORS: Record<string, CorridorEntity> = {
  corr_rift_nairobi_mombasa: {
    canonicalId: 'corr_rift_nairobi_mombasa',
    code: 'CORR-400-RNM',
    name: 'Suswa – Isinya – Mombasa 400kV Eastern Backbone Corridor',
    type: 'CORRIDOR',
    voltageKV: 400,
    corridorCode: 'RNM-400',
    location: {
      latitude: -2.35,
      longitude: 37.95,
      region: 'COAST',
      county: 'Kilifi / Kajiado / Narok'
    },
    state: 'NORMAL',
    health: 94,
    risk: 18,
    timestamp: new Date().toISOString(),
    source: 'GIS_POSTGIS',
    confidence: 99.1,
    reconciliationStatus: 'VERIFIED',
    sourceIds: {
      gisId: 'GIS-CORR-001-RNM',
      engineeringId: 'ENG-CORR-400-SE-01'
    },
    lineIds: ['tl_ssw_isy', 'tl_isy_mrk', 'tl_mrk_rab'],
    substationIds: ['suswa', 'isinya', 'mariakani', 'rabai'],
    totalTransferCapabilityMW: 2400,
    actualTransferMW: 1420,
    congestionIndexPct: 59.2,
    dynamicLineRatingGainPct: 14.5,
    terrainType: 'SAVANNAH'
  },
  corr_hvdc_ethiopia_kenya: {
    canonicalId: 'corr_hvdc_ethiopia_kenya',
    code: 'CORR-500-HVDC',
    name: 'Eastern Africa Power Pool 500kV HVDC Bipole Corridor',
    type: 'CORRIDOR',
    voltageKV: 500,
    corridorCode: 'EAPP-500',
    location: {
      latitude: 1.85,
      longitude: 37.65,
      region: 'NORTH_EASTERN',
      county: 'Marsabit / Samburu / Isiolo'
    },
    state: 'NORMAL',
    health: 98,
    risk: 12,
    timestamp: new Date().toISOString(),
    source: 'SCADA_EMS',
    confidence: 99.8,
    reconciliationStatus: 'VERIFIED',
    sourceIds: {
      scadaId: 'SCD-EAPP-HVDC-500',
      gisId: 'GIS-CORR-002-HVDC',
      engineeringId: 'ENG-CORR-500-BIPOLE'
    },
    lineIds: ['tl_hvdc_eth_ken'],
    substationIds: ['moyale_hvdc', 'suswa'],
    totalTransferCapabilityMW: 2000,
    actualTransferMW: 850,
    congestionIndexPct: 42.5,
    dynamicLineRatingGainPct: 18.2,
    terrainType: 'ARID_NORTH'
  },
  corr_olkaria_lessos_kisumu: {
    canonicalId: 'corr_olkaria_lessos_kisumu',
    code: 'CORR-400-OLK-KSM',
    name: 'Olkaria – Lessos – Kisumu 400kV / 220kV Western Green Corridor',
    type: 'CORRIDOR',
    voltageKV: 400,
    corridorCode: 'OLK-W-400',
    location: {
      latitude: 0.12,
      longitude: 35.25,
      region: 'WESTERN',
      county: 'Nakuru / Nandi / Kisumu'
    },
    state: 'NORMAL',
    health: 91,
    risk: 24,
    timestamp: new Date().toISOString(),
    source: 'WAMS_PMU',
    confidence: 98.4,
    reconciliationStatus: 'VERIFIED',
    sourceIds: {
      gisId: 'GIS-CORR-003-WGN',
      scadaId: 'SCD-CORR-WGN-01'
    },
    lineIds: ['tl_olk_les', 'tl_les_ksm', 'tl_ssw_olk'],
    substationIds: ['suswa', 'olkaria', 'lessos', 'kisumu'],
    totalTransferCapabilityMW: 1200,
    actualTransferMW: 680,
    congestionIndexPct: 56.6,
    dynamicLineRatingGainPct: 9.8,
    terrainType: 'HIGHLANDS'
  },
  corr_nairobi_220_ring: {
    canonicalId: 'corr_nairobi_220_ring',
    code: 'CORR-220-NBI-RING',
    name: 'Nairobi Metropolitan 220kV Underground & Overhead Reinforcement Ring',
    type: 'CORRIDOR',
    voltageKV: 220,
    corridorCode: 'NRB-RING-220',
    location: {
      latitude: -1.30,
      longitude: 36.88,
      region: 'NAIROBI',
      county: 'Nairobi / Kiambu / Machakos'
    },
    state: 'CONGESTED',
    health: 76,
    risk: 74,
    timestamp: new Date().toISOString(),
    source: 'SCADA_EMS',
    confidence: 97.2,
    reconciliationStatus: 'HIGH',
    sourceIds: {
      scadaId: 'SCD-RING-220-01',
      gisId: 'GIS-CORR-004-NRB',
      eamId: 'EAM-CORR-RING-NBI'
    },
    lineIds: ['tl_ssw_nbn', 'tl_nbn_emb', 'tl_emb_dan', 'tl_isy_emb'],
    substationIds: ['suswa', 'nairobi_north', 'embakasi', 'dandora', 'isinya'],
    totalTransferCapabilityMW: 1800,
    actualTransferMW: 1605,
    congestionIndexPct: 89.2,
    dynamicLineRatingGainPct: 3.1,
    terrainType: 'HIGHLANDS'
  }
};

// ============================================================================
// CANONICAL SUBSTATIONS DATASET
// ============================================================================
export const CANONICAL_SUBSTATIONS_V2: Record<string, SubstationEntity> = {
  suswa: {
    canonicalId: 'suswa',
    code: 'SSW-500-01',
    name: 'Suswa 500kV / 400kV EHV Hub',
    type: 'SUBSTATION',
    voltageKV: 500,
    location: {
      latitude: -1.0543,
      longitude: 36.3532,
      elevationM: 1890,
      region: 'RIFT_VALLEY',
      county: 'Narok',
      coordinates: { x: 310, y: 320 }
    },
    state: 'WARNING',
    health: 78,
    risk: 68,
    timestamp: new Date().toISOString(),
    source: 'SCADA_EMS',
    confidence: 98.4,
    reconciliationStatus: 'VERIFIED',
    sourceIds: {
      scadaId: 'SCD-KTR-SSW-01',
      gisId: 'GIS-NODE-88412',
      eamId: 'EAM-SAP-EQ-10029',
      pmuId: 'PMU-SSW-500-A',
      engineeringId: 'ENG-DWG-500-SSW-A'
    },
    ratedCapacityMVA: 1500,
    currentLoadMW: 1145,
    peakLoadMW: 1320,
    criticalityScore: 10,
    nMinusOneRedundant: true,
    singlePointOfFailure: false,
    telemetry: {
      activePowerMW: { value: 1145, unit: 'MW', timestamp: new Date().toISOString(), source: 'SCADA_EMS', quality: 'GOOD', freshness: 'LIVE', confidence: 99 },
      reactivePowerMVAR: { value: 182, unit: 'MVAR', timestamp: new Date().toISOString(), source: 'SCADA_EMS', quality: 'GOOD', freshness: 'LIVE', confidence: 98 },
      voltageKV: { value: 508.2, unit: 'kV', timestamp: new Date().toISOString(), source: 'WAMS_PMU', quality: 'GOOD', freshness: 'LIVE', confidence: 99.5 },
      frequencyHz: { value: 50.02, unit: 'Hz', timestamp: new Date().toISOString(), source: 'WAMS_PMU', quality: 'GOOD', freshness: 'LIVE', confidence: 99.9 },
      thermalLoadingPct: { value: 81.4, unit: '%', timestamp: new Date().toISOString(), source: 'SCADA_EMS', quality: 'GOOD', freshness: 'LIVE', confidence: 97 },
      transformerOilTempC: { value: 68.5, unit: '°C', timestamp: new Date().toISOString(), source: 'SCADA_EMS', quality: 'GOOD', freshness: 'LIVE', confidence: 96 },
      sf6PressureBar: { value: 6.2, unit: 'bar', timestamp: new Date().toISOString(), source: 'SCADA_EMS', quality: 'GOOD', freshness: 'LIVE', confidence: 98 },
      powerFactor: { value: 0.98, unit: 'PF', timestamp: new Date().toISOString(), source: 'SCADA_EMS', quality: 'GOOD', freshness: 'LIVE', confidence: 99 }
    },
    bayIds: ['bay_ssw_500_01', 'bay_ssw_400_01', 'bay_ssw_400_02'],
    transformerIds: ['tx_ssw_t1', 'tx_ssw_t2', 'tx_ssw_t3'],
    breakerIds: ['cb_ssw_501', 'cb_ssw_502', 'cb_ssw_401', 'cb_ssw_402'],
    busbarIds: ['bus_ssw_500_main', 'bus_ssw_400_main'],
    relayIds: ['rel_ssw_87l_01', 'rel_ssw_21_01', 'rel_ssw_87t_01'],
    generationIds: [],
    loadIds: ['load_ssw_aux'],
    corridorIds: ['corr_rift_nairobi_mombasa', 'corr_hvdc_ethiopia_kenya', 'corr_olkaria_lessos_kisumu', 'corr_nairobi_220_ring'],
    connectedLines: ['tl_ssw_olk', 'tl_ssw_isy', 'tl_ssw_nbn', 'tl_hvdc_eth_ken', 'tl_loy_ssw'],
    connectedSubstations: ['olkaria', 'isinya', 'nairobi_north', 'loiyangalani', 'moyale_hvdc'],
    downstreamNodes: ['nairobi_north', 'isinya', 'nairobi_ring'],
    upstreamNodes: ['olkaria', 'loiyangalani', 'moyale_hvdc'],
    alternativePaths: ['olkaria -> lessos -> kisumu', 'isinya -> mariakani -> rabai']
  },
  olkaria: {
    canonicalId: 'olkaria',
    code: 'OLK-400-01',
    name: 'Olkaria Geothermal Switching Station',
    type: 'GENERATOR_INTERFACE',
    voltageKV: 400,
    location: {
      latitude: -0.8842,
      longitude: 36.3012,
      elevationM: 1950,
      region: 'RIFT_VALLEY',
      county: 'Nakuru',
      coordinates: { x: 260, y: 280 }
    },
    state: 'NORMAL',
    health: 96,
    risk: 14,
    timestamp: new Date().toISOString(),
    source: 'SCADA_EMS',
    confidence: 99.2,
    reconciliationStatus: 'VERIFIED',
    sourceIds: {
      scadaId: 'SCD-KTR-OLK-01',
      gisId: 'GIS-NODE-88415',
      eamId: 'EAM-SAP-EQ-10034',
      pmuId: 'PMU-OLK-400-01',
      engineeringId: 'ENG-DWG-400-OLK-B'
    },
    ratedCapacityMVA: 1200,
    currentLoadMW: 892,
    peakLoadMW: 960,
    criticalityScore: 9,
    nMinusOneRedundant: true,
    singlePointOfFailure: false,
    telemetry: {
      activePowerMW: { value: 892, unit: 'MW', timestamp: new Date().toISOString(), source: 'SCADA_EMS', quality: 'GOOD', freshness: 'LIVE', confidence: 99 },
      reactivePowerMVAR: { value: 110, unit: 'MVAR', timestamp: new Date().toISOString(), source: 'SCADA_EMS', quality: 'GOOD', freshness: 'LIVE', confidence: 98 },
      voltageKV: { value: 402.1, unit: 'kV', timestamp: new Date().toISOString(), source: 'WAMS_PMU', quality: 'GOOD', freshness: 'LIVE', confidence: 99.7 },
      frequencyHz: { value: 50.01, unit: 'Hz', timestamp: new Date().toISOString(), source: 'WAMS_PMU', quality: 'GOOD', freshness: 'LIVE', confidence: 99.9 },
      thermalLoadingPct: { value: 64.2, unit: '%', timestamp: new Date().toISOString(), source: 'SCADA_EMS', quality: 'GOOD', freshness: 'LIVE', confidence: 98 },
      transformerOilTempC: { value: 54.1, unit: '°C', timestamp: new Date().toISOString(), source: 'SCADA_EMS', quality: 'GOOD', freshness: 'LIVE', confidence: 97 },
      sf6PressureBar: { value: 6.5, unit: 'bar', timestamp: new Date().toISOString(), source: 'SCADA_EMS', quality: 'GOOD', freshness: 'LIVE', confidence: 99 },
      powerFactor: { value: 0.99, unit: 'PF', timestamp: new Date().toISOString(), source: 'SCADA_EMS', quality: 'GOOD', freshness: 'LIVE', confidence: 99 }
    },
    bayIds: ['bay_olk_400_01', 'bay_olk_400_02'],
    transformerIds: ['tx_olk_t1', 'tx_olk_t2'],
    breakerIds: ['cb_olk_401', 'cb_olk_402'],
    busbarIds: ['bus_olk_400_main'],
    relayIds: ['rel_olk_87l_01', 'rel_olk_21_01'],
    generationIds: ['gen_olk_geo_iv', 'gen_olk_geo_v'],
    loadIds: [],
    corridorIds: ['corr_olkaria_lessos_kisumu', 'corr_rift_nairobi_mombasa'],
    connectedLines: ['tl_ssw_olk', 'tl_olk_les'],
    connectedSubstations: ['suswa', 'lessos'],
    downstreamNodes: ['suswa', 'lessos'],
    upstreamNodes: ['olkaria_plants'],
    alternativePaths: ['olkaria -> lessos -> kisumu']
  },
  isinya: {
    canonicalId: 'isinya',
    code: 'ISN-400-01',
    name: 'Isinya 400kV / 220kV Interconnector Substation',
    type: 'SUBSTATION',
    voltageKV: 400,
    location: {
      latitude: -1.6721,
      longitude: 36.8543,
      elevationM: 1650,
      region: 'CENTRAL',
      county: 'Kajiado',
      coordinates: { x: 380, y: 390 }
    },
    state: 'NORMAL',
    health: 92,
    risk: 22,
    timestamp: new Date().toISOString(),
    source: 'SCADA_EMS',
    confidence: 97.8,
    reconciliationStatus: 'VERIFIED',
    sourceIds: {
      scadaId: 'SCD-KTR-ISN-01',
      gisId: 'GIS-NODE-88420',
      eamId: 'EAM-SAP-EQ-10055',
      engineeringId: 'ENG-DWG-400-ISN-01'
    },
    ratedCapacityMVA: 1000,
    currentLoadMW: 720,
    peakLoadMW: 840,
    criticalityScore: 9,
    nMinusOneRedundant: true,
    singlePointOfFailure: false,
    telemetry: {
      activePowerMW: { value: 720, unit: 'MW', timestamp: new Date().toISOString(), source: 'SCADA_EMS', quality: 'GOOD', freshness: 'LIVE', confidence: 99 },
      reactivePowerMVAR: { value: 85, unit: 'MVAR', timestamp: new Date().toISOString(), source: 'SCADA_EMS', quality: 'GOOD', freshness: 'LIVE', confidence: 97 },
      voltageKV: { value: 399.8, unit: 'kV', timestamp: new Date().toISOString(), source: 'WAMS_PMU', quality: 'GOOD', freshness: 'LIVE', confidence: 99.4 },
      frequencyHz: { value: 50.01, unit: 'Hz', timestamp: new Date().toISOString(), source: 'WAMS_PMU', quality: 'GOOD', freshness: 'LIVE', confidence: 99.9 },
      thermalLoadingPct: { value: 58.0, unit: '%', timestamp: new Date().toISOString(), source: 'SCADA_EMS', quality: 'GOOD', freshness: 'LIVE', confidence: 98 },
      transformerOilTempC: { value: 51.2, unit: '°C', timestamp: new Date().toISOString(), source: 'SCADA_EMS', quality: 'GOOD', freshness: 'LIVE', confidence: 98 },
      sf6PressureBar: { value: 6.4, unit: 'bar', timestamp: new Date().toISOString(), source: 'SCADA_EMS', quality: 'GOOD', freshness: 'LIVE', confidence: 99 },
      powerFactor: { value: 0.97, unit: 'PF', timestamp: new Date().toISOString(), source: 'SCADA_EMS', quality: 'GOOD', freshness: 'LIVE', confidence: 99 }
    },
    bayIds: ['bay_isn_400_01', 'bay_isn_220_01'],
    transformerIds: ['tx_isn_t1', 'tx_isn_t2'],
    breakerIds: ['cb_isn_401', 'cb_isn_221'],
    busbarIds: ['bus_isn_400_main', 'bus_isn_220_main'],
    relayIds: ['rel_isn_87l_01'],
    generationIds: [],
    loadIds: ['load_kajiado_south'],
    corridorIds: ['corr_rift_nairobi_mombasa', 'corr_nairobi_220_ring'],
    connectedLines: ['tl_ssw_isy', 'tl_isy_mrk', 'tl_isy_emb', 'tl_isy_tz_inter'],
    connectedSubstations: ['suswa', 'mariakani', 'embakasi', 'namanga_tz'],
    downstreamNodes: ['mariakani', 'embakasi'],
    upstreamNodes: ['suswa'],
    alternativePaths: ['suswa -> nairobi_north -> embakasi', 'mariakani -> rabai']
  },
  embakasi: {
    canonicalId: 'embakasi',
    code: 'EMB-220-01',
    name: 'Embakasi 220kV / 66kV Metro Primary Substation',
    type: 'SUBSTATION',
    voltageKV: 220,
    location: {
      latitude: -1.3211,
      longitude: 36.8924,
      elevationM: 1620,
      region: 'NAIROBI',
      county: 'Nairobi',
      coordinates: { x: 420, y: 340 }
    },
    state: 'CRITICAL',
    health: 62,
    risk: 84,
    timestamp: new Date().toISOString(),
    source: 'SCADA_EMS',
    confidence: 96.5,
    reconciliationStatus: 'VERIFIED',
    sourceIds: {
      scadaId: 'SCD-KTR-EMB-01',
      gisId: 'GIS-NODE-88432',
      eamId: 'EAM-SAP-EQ-10089',
      engineeringId: 'ENG-DWG-220-EMB-C'
    },
    ratedCapacityMVA: 660,
    currentLoadMW: 588,
    peakLoadMW: 615,
    criticalityScore: 10,
    nMinusOneRedundant: false,
    singlePointOfFailure: true,
    telemetry: {
      activePowerMW: { value: 588, unit: 'MW', timestamp: new Date().toISOString(), source: 'SCADA_EMS', quality: 'QUESTIONABLE', freshness: 'LIVE', confidence: 92 },
      reactivePowerMVAR: { value: 142, unit: 'MVAR', timestamp: new Date().toISOString(), source: 'SCADA_EMS', quality: 'GOOD', freshness: 'LIVE', confidence: 95 },
      voltageKV: { value: 214.8, unit: 'kV', timestamp: new Date().toISOString(), source: 'WAMS_PMU', quality: 'GOOD', freshness: 'LIVE', confidence: 99.1 },
      frequencyHz: { value: 49.99, unit: 'Hz', timestamp: new Date().toISOString(), source: 'WAMS_PMU', quality: 'GOOD', freshness: 'LIVE', confidence: 99.8 },
      thermalLoadingPct: { value: 89.1, unit: '%', timestamp: new Date().toISOString(), source: 'SCADA_EMS', quality: 'GOOD', freshness: 'LIVE', confidence: 98 },
      transformerOilTempC: { value: 74.2, unit: '°C', timestamp: new Date().toISOString(), source: 'SCADA_EMS', quality: 'GOOD', freshness: 'LIVE', confidence: 97 },
      sf6PressureBar: { value: 5.9, unit: 'bar', timestamp: new Date().toISOString(), source: 'SCADA_EMS', quality: 'GOOD', freshness: 'LIVE', confidence: 94 },
      powerFactor: { value: 0.94, unit: 'PF', timestamp: new Date().toISOString(), source: 'SCADA_EMS', quality: 'GOOD', freshness: 'LIVE', confidence: 98 }
    },
    bayIds: ['bay_emb_220_01', 'bay_emb_66_01'],
    transformerIds: ['tx_emb_t1', 'tx_emb_t2'],
    breakerIds: ['cb_emb_201', 'cb_emb_601'],
    busbarIds: ['bus_emb_220_main', 'bus_emb_66_main'],
    relayIds: ['rel_emb_87t_01', 'rel_emb_50_01'],
    generationIds: [],
    loadIds: ['load_nbi_cbd', 'load_nbi_industrial'],
    corridorIds: ['corr_nairobi_220_ring'],
    connectedLines: ['tl_nbn_emb', 'tl_emb_dan', 'tl_isy_emb'],
    connectedSubstations: ['nairobi_north', 'dandora', 'isinya'],
    downstreamNodes: ['dandora', 'nairobi_cbd_feeders'],
    upstreamNodes: ['nairobi_north', 'isinya'],
    alternativePaths: ['nairobi_north -> juja -> dandora']
  },
  mariakani: {
    canonicalId: 'mariakani',
    code: 'MRK-400-01',
    name: 'Mariakani 400kV / 220kV Coastal Hub',
    type: 'SUBSTATION',
    voltageKV: 400,
    location: {
      latitude: -3.8642,
      longitude: 39.4721,
      elevationM: 190,
      region: 'COAST',
      county: 'Kilifi',
      coordinates: { x: 590, y: 540 }
    },
    state: 'NORMAL',
    health: 93,
    risk: 18,
    timestamp: new Date().toISOString(),
    source: 'SCADA_EMS',
    confidence: 98.1,
    reconciliationStatus: 'VERIFIED',
    sourceIds: {
      scadaId: 'SCD-KTR-MRK-01',
      gisId: 'GIS-NODE-88450',
      eamId: 'EAM-SAP-EQ-10110',
      engineeringId: 'ENG-DWG-400-MRK-01'
    },
    ratedCapacityMVA: 800,
    currentLoadMW: 440,
    peakLoadMW: 520,
    criticalityScore: 9,
    nMinusOneRedundant: true,
    singlePointOfFailure: false,
    telemetry: {
      activePowerMW: { value: 440, unit: 'MW', timestamp: new Date().toISOString(), source: 'SCADA_EMS', quality: 'GOOD', freshness: 'LIVE', confidence: 99 },
      reactivePowerMVAR: { value: 65, unit: 'MVAR', timestamp: new Date().toISOString(), source: 'SCADA_EMS', quality: 'GOOD', freshness: 'LIVE', confidence: 97 },
      voltageKV: { value: 401.4, unit: 'kV', timestamp: new Date().toISOString(), source: 'WAMS_PMU', quality: 'GOOD', freshness: 'LIVE', confidence: 99.6 },
      frequencyHz: { value: 50.01, unit: 'Hz', timestamp: new Date().toISOString(), source: 'WAMS_PMU', quality: 'GOOD', freshness: 'LIVE', confidence: 99.9 },
      thermalLoadingPct: { value: 48.6, unit: '%', timestamp: new Date().toISOString(), source: 'SCADA_EMS', quality: 'GOOD', freshness: 'LIVE', confidence: 98 },
      transformerOilTempC: { value: 48.0, unit: '°C', timestamp: new Date().toISOString(), source: 'SCADA_EMS', quality: 'GOOD', freshness: 'LIVE', confidence: 97 },
      sf6PressureBar: { value: 6.4, unit: 'bar', timestamp: new Date().toISOString(), source: 'SCADA_EMS', quality: 'GOOD', freshness: 'LIVE', confidence: 99 },
      powerFactor: { value: 0.98, unit: 'PF', timestamp: new Date().toISOString(), source: 'SCADA_EMS', quality: 'GOOD', freshness: 'LIVE', confidence: 99 }
    },
    bayIds: ['bay_mrk_400_01', 'bay_mrk_220_01'],
    transformerIds: ['tx_mrk_t1'],
    breakerIds: ['cb_mrk_401'],
    busbarIds: ['bus_mrk_400_main'],
    relayIds: ['rel_mrk_87l_01'],
    generationIds: [],
    loadIds: ['load_kilifi_coast'],
    corridorIds: ['corr_rift_nairobi_mombasa'],
    connectedLines: ['tl_isy_mrk', 'tl_mrk_rab', 'tl_mrk_diani'],
    connectedSubstations: ['isinya', 'rabai', 'diani'],
    downstreamNodes: ['rabai', 'diani', 'mombasa_island'],
    upstreamNodes: ['isinya'],
    alternativePaths: ['isinya -> rabai (via direct 220kV aux)']
  },
  rabai: {
    canonicalId: 'rabai',
    code: 'RAB-220-01',
    name: 'Rabai 220kV / 132kV Mombasa Distribution Terminal',
    type: 'SUBSTATION',
    voltageKV: 220,
    location: {
      latitude: -3.9312,
      longitude: 39.5643,
      elevationM: 85,
      region: 'COAST',
      county: 'Kilifi',
      coordinates: { x: 620, y: 570 }
    },
    state: 'NORMAL',
    health: 88,
    risk: 28,
    timestamp: new Date().toISOString(),
    source: 'SCADA_EMS',
    confidence: 97.4,
    reconciliationStatus: 'VERIFIED',
    sourceIds: {
      scadaId: 'SCD-KTR-RAB-01',
      gisId: 'GIS-NODE-88458',
      eamId: 'EAM-SAP-EQ-10118'
    },
    ratedCapacityMVA: 500,
    currentLoadMW: 375,
    peakLoadMW: 420,
    criticalityScore: 8,
    nMinusOneRedundant: true,
    singlePointOfFailure: false,
    telemetry: {
      activePowerMW: { value: 375, unit: 'MW', timestamp: new Date().toISOString(), source: 'SCADA_EMS', quality: 'GOOD', freshness: 'LIVE', confidence: 99 },
      reactivePowerMVAR: { value: 52, unit: 'MVAR', timestamp: new Date().toISOString(), source: 'SCADA_EMS', quality: 'GOOD', freshness: 'LIVE', confidence: 98 },
      voltageKV: { value: 220.6, unit: 'kV', timestamp: new Date().toISOString(), source: 'WAMS_PMU', quality: 'GOOD', freshness: 'LIVE', confidence: 99.5 },
      frequencyHz: { value: 50.01, unit: 'Hz', timestamp: new Date().toISOString(), source: 'WAMS_PMU', quality: 'GOOD', freshness: 'LIVE', confidence: 99.9 },
      thermalLoadingPct: { value: 62.1, unit: '%', timestamp: new Date().toISOString(), source: 'SCADA_EMS', quality: 'GOOD', freshness: 'LIVE', confidence: 98 },
      transformerOilTempC: { value: 56.4, unit: '°C', timestamp: new Date().toISOString(), source: 'SCADA_EMS', quality: 'GOOD', freshness: 'LIVE', confidence: 97 },
      sf6PressureBar: { value: 6.3, unit: 'bar', timestamp: new Date().toISOString(), source: 'SCADA_EMS', quality: 'GOOD', freshness: 'LIVE', confidence: 99 },
      powerFactor: { value: 0.97, unit: 'PF', timestamp: new Date().toISOString(), source: 'SCADA_EMS', quality: 'GOOD', freshness: 'LIVE', confidence: 99 }
    },
    bayIds: ['bay_rab_220_01'],
    transformerIds: ['tx_rab_t1'],
    breakerIds: ['cb_rab_201'],
    busbarIds: ['bus_rab_220_main'],
    relayIds: ['rel_rab_87l_01'],
    generationIds: ['gen_kipevu_diesel'],
    loadIds: ['load_mombasa_port', 'load_mombasa_metro'],
    corridorIds: ['corr_rift_nairobi_mombasa'],
    connectedLines: ['tl_mrk_rab', 'tl_rab_kpv'],
    connectedSubstations: ['mariakani', 'kipevu'],
    downstreamNodes: ['kipevu', 'mombasa_port'],
    upstreamNodes: ['mariakani'],
    alternativePaths: ['mariakani -> bamburi -> rabai']
  },
  loiyangalani: {
    canonicalId: 'loiyangalani',
    code: 'LOY-400-01',
    name: 'Loiyangalani 400kV Wind Terminal Switching Station',
    type: 'GENERATOR_INTERFACE',
    voltageKV: 400,
    location: {
      latitude: 2.7541,
      longitude: 36.7124,
      elevationM: 375,
      region: 'NORTH_EASTERN',
      county: 'Marsabit',
      coordinates: { x: 360, y: 130 }
    },
    state: 'NORMAL',
    health: 94,
    risk: 18,
    timestamp: new Date().toISOString(),
    source: 'SCADA_EMS',
    confidence: 98.9,
    reconciliationStatus: 'VERIFIED',
    sourceIds: {
      scadaId: 'SCD-KTR-LOY-01',
      gisId: 'GIS-NODE-88402',
      eamId: 'EAM-SAP-EQ-10012'
    },
    ratedCapacityMVA: 800,
    currentLoadMW: 295,
    peakLoadMW: 310,
    criticalityScore: 9,
    nMinusOneRedundant: true,
    singlePointOfFailure: false,
    telemetry: {
      activePowerMW: { value: 295, unit: 'MW', timestamp: new Date().toISOString(), source: 'SCADA_EMS', quality: 'GOOD', freshness: 'LIVE', confidence: 99 },
      reactivePowerMVAR: { value: 38, unit: 'MVAR', timestamp: new Date().toISOString(), source: 'SCADA_EMS', quality: 'GOOD', freshness: 'LIVE', confidence: 98 },
      voltageKV: { value: 403.8, unit: 'kV', timestamp: new Date().toISOString(), source: 'WAMS_PMU', quality: 'GOOD', freshness: 'LIVE', confidence: 99.8 },
      frequencyHz: { value: 50.02, unit: 'Hz', timestamp: new Date().toISOString(), source: 'WAMS_PMU', quality: 'GOOD', freshness: 'LIVE', confidence: 99.9 },
      thermalLoadingPct: { value: 44.5, unit: '%', timestamp: new Date().toISOString(), source: 'SCADA_EMS', quality: 'GOOD', freshness: 'LIVE', confidence: 98 },
      transformerOilTempC: { value: 46.8, unit: '°C', timestamp: new Date().toISOString(), source: 'SCADA_EMS', quality: 'GOOD', freshness: 'LIVE', confidence: 98 },
      sf6PressureBar: { value: 6.5, unit: 'bar', timestamp: new Date().toISOString(), source: 'SCADA_EMS', quality: 'GOOD', freshness: 'LIVE', confidence: 99 },
      powerFactor: { value: 0.99, unit: 'PF', timestamp: new Date().toISOString(), source: 'SCADA_EMS', quality: 'GOOD', freshness: 'LIVE', confidence: 99 }
    },
    bayIds: ['bay_loy_400_01'],
    transformerIds: ['tx_loy_t1'],
    breakerIds: ['cb_loy_401'],
    busbarIds: ['bus_loy_400_main'],
    relayIds: ['rel_loy_87l_01'],
    generationIds: ['gen_ltwp_310mw'],
    loadIds: [],
    corridorIds: ['corr_hvdc_ethiopia_kenya'],
    connectedLines: ['tl_loy_ssw'],
    connectedSubstations: ['suswa'],
    downstreamNodes: ['suswa'],
    upstreamNodes: ['lake_turkana_wind_power_farm'],
    alternativePaths: []
  },
  moyale_hvdc: {
    canonicalId: 'moyale_hvdc',
    code: 'MYL-500-01',
    name: 'Moyale 500kV HVDC Converter Border Station',
    type: 'HVDC_CONVERTER',
    voltageKV: 500,
    location: {
      latitude: 3.5241,
      longitude: 39.0543,
      elevationM: 1100,
      region: 'NORTH_EASTERN',
      county: 'Marsabit',
      coordinates: { x: 520, y: 60 }
    },
    state: 'NORMAL',
    health: 97,
    risk: 15,
    timestamp: new Date().toISOString(),
    source: 'SCADA_EMS',
    confidence: 99.4,
    reconciliationStatus: 'VERIFIED',
    sourceIds: {
      scadaId: 'SCD-KTR-MYL-01',
      gisId: 'GIS-NODE-88401',
      eamId: 'EAM-SAP-EQ-10001'
    },
    ratedCapacityMVA: 2000,
    currentLoadMW: 850,
    peakLoadMW: 1000,
    criticalityScore: 10,
    nMinusOneRedundant: true,
    singlePointOfFailure: false,
    telemetry: {
      activePowerMW: { value: 850, unit: 'MW', timestamp: new Date().toISOString(), source: 'SCADA_EMS', quality: 'GOOD', freshness: 'LIVE', confidence: 99 },
      reactivePowerMVAR: { value: 40, unit: 'MVAR', timestamp: new Date().toISOString(), source: 'SCADA_EMS', quality: 'GOOD', freshness: 'LIVE', confidence: 98 },
      voltageKV: { value: 501.2, unit: 'kV', timestamp: new Date().toISOString(), source: 'WAMS_PMU', quality: 'GOOD', freshness: 'LIVE', confidence: 99.9 },
      frequencyHz: { value: 50.00, unit: 'Hz', timestamp: new Date().toISOString(), source: 'WAMS_PMU', quality: 'GOOD', freshness: 'LIVE', confidence: 99.9 },
      thermalLoadingPct: { value: 42.5, unit: '%', timestamp: new Date().toISOString(), source: 'SCADA_EMS', quality: 'GOOD', freshness: 'LIVE', confidence: 98 },
      transformerOilTempC: { value: 52.1, unit: '°C', timestamp: new Date().toISOString(), source: 'SCADA_EMS', quality: 'GOOD', freshness: 'LIVE', confidence: 98 },
      sf6PressureBar: { value: 6.6, unit: 'bar', timestamp: new Date().toISOString(), source: 'SCADA_EMS', quality: 'GOOD', freshness: 'LIVE', confidence: 99 },
      powerFactor: { value: 0.99, unit: 'PF', timestamp: new Date().toISOString(), source: 'SCADA_EMS', quality: 'GOOD', freshness: 'LIVE', confidence: 99 }
    },
    bayIds: ['bay_myl_500_01'],
    transformerIds: ['tx_myl_converter_t1'],
    breakerIds: ['cb_myl_501'],
    busbarIds: ['bus_myl_500_dc'],
    relayIds: ['rel_myl_hvdc_diff_01'],
    generationIds: ['gen_eapp_ethiopia_import'],
    loadIds: [],
    corridorIds: ['corr_hvdc_ethiopia_kenya'],
    connectedLines: ['tl_hvdc_eth_ken'],
    connectedSubstations: ['suswa'],
    downstreamNodes: ['suswa'],
    upstreamNodes: ['ethiopia_eapp_grid'],
    alternativePaths: []
  }
};

// ============================================================================
// CANONICAL SUBSTATION EQUIPMENT (TRANSFORMERS, BREAKERS, BAYS, RELAYS)
// ============================================================================
export const CANONICAL_TRANSFORMERS: Record<string, TransformerEntity> = {
  tx_ssw_t1: {
    canonicalId: 'tx_ssw_t1',
    code: 'SSW-TX-01',
    name: 'Suswa Auto-Transformer T1 (500/400kV, 500MVA)',
    type: 'TRANSFORMER',
    voltageKV: 500,
    substationId: 'suswa',
    bayId: 'bay_ssw_500_01',
    mvaRating: 500,
    primaryVoltageKV: 500,
    secondaryVoltageKV: 400,
    tertiaryVoltageKV: 33,
    coolingType: 'ODAF',
    oilTemperatureC: 68.5,
    windingTemperatureC: 84.1,
    dgaStatus: 'NORMAL',
    hydrogenPpm: 18,
    acetylenePpm: 0.2,
    ethylenePpm: 4.1,
    tapPosition: 7,
    loadingPct: 81.4,
    maintenanceDueDays: 142,
    health: 86,
    risk: 32,
    state: 'NORMAL',
    location: { latitude: -1.0543, longitude: 36.3532, region: 'RIFT_VALLEY' },
    source: 'SCADA_EMS',
    confidence: 98.6,
    reconciliationStatus: 'VERIFIED',
    sourceIds: {
      scadaId: 'SCD-TX-SSW-01',
      eamId: 'EAM-EQ-SSW-TX1',
      gisId: 'GIS-EQ-88412-TX1'
    },
    timestamp: new Date().toISOString()
  },
  tx_ssw_t2: {
    canonicalId: 'tx_ssw_t2',
    code: 'SSW-TX-02',
    name: 'Suswa Auto-Transformer T2 (500/400kV, 500MVA)',
    type: 'TRANSFORMER',
    voltageKV: 500,
    substationId: 'suswa',
    bayId: 'bay_ssw_500_02',
    mvaRating: 500,
    primaryVoltageKV: 500,
    secondaryVoltageKV: 400,
    tertiaryVoltageKV: 33,
    coolingType: 'ODAF',
    oilTemperatureC: 71.2,
    windingTemperatureC: 88.5,
    dgaStatus: 'CAUTION',
    hydrogenPpm: 48,
    acetylenePpm: 1.4,
    ethylenePpm: 12.8,
    tapPosition: 8,
    loadingPct: 83.2,
    maintenanceDueDays: 6,
    health: 74,
    risk: 62,
    state: 'WARNING',
    location: { latitude: -1.0543, longitude: 36.3532, region: 'RIFT_VALLEY' },
    source: 'EAM_SAP',
    confidence: 97.4,
    reconciliationStatus: 'VERIFIED',
    sourceIds: {
      scadaId: 'SCD-TX-SSW-02',
      eamId: 'EAM-EQ-SSW-TX2',
      gisId: 'GIS-EQ-88412-TX2'
    },
    timestamp: new Date().toISOString()
  },
  tx_emb_t1: {
    canonicalId: 'tx_emb_t1',
    code: 'EMB-TX-01',
    name: 'Embakasi Step-Down Transformer T1 (220/66kV, 330MVA)',
    type: 'TRANSFORMER',
    voltageKV: 220,
    substationId: 'embakasi',
    bayId: 'bay_emb_220_01',
    mvaRating: 330,
    primaryVoltageKV: 220,
    secondaryVoltageKV: 66,
    coolingType: 'ONAF',
    oilTemperatureC: 74.2,
    windingTemperatureC: 92.4,
    dgaStatus: 'CAUTION',
    hydrogenPpm: 64,
    acetylenePpm: 2.1,
    ethylenePpm: 16.5,
    tapPosition: 11,
    loadingPct: 89.1,
    maintenanceDueDays: 14,
    health: 64,
    risk: 78,
    state: 'WARNING',
    location: { latitude: -1.3211, longitude: 36.8924, region: 'NAIROBI' },
    source: 'SCADA_EMS',
    confidence: 96.1,
    reconciliationStatus: 'VERIFIED',
    sourceIds: {
      scadaId: 'SCD-TX-EMB-01',
      eamId: 'EAM-EQ-EMB-TX1'
    },
    timestamp: new Date().toISOString()
  }
};

export const CANONICAL_BREAKERS: Record<string, BreakerEntity> = {
  cb_ssw_501: {
    canonicalId: 'cb_ssw_501',
    code: 'CB-SSW-501',
    name: 'Suswa 500kV Feeder Circuit Breaker Q01',
    type: 'CIRCUIT_BREAKER',
    voltageKV: 500,
    substationId: 'suswa',
    bayId: 'bay_ssw_500_01',
    position: 'CLOSED',
    sf6PressureBar: 6.2,
    contactWearPct: 18.4,
    tripOperationsCount: 42,
    ratedCurrentA: 4000,
    interruptionCapacityKA: 63,
    operatingMechanism: 'HYDRAULIC',
    health: 92,
    risk: 16,
    state: 'NORMAL',
    location: { latitude: -1.0543, longitude: 36.3532, region: 'RIFT_VALLEY' },
    source: 'SCADA_EMS',
    confidence: 99.2,
    reconciliationStatus: 'VERIFIED',
    sourceIds: {
      scadaId: 'SCD-CB-SSW-501',
      eamId: 'EAM-EQ-SSW-CB501'
    },
    timestamp: new Date().toISOString()
  },
  cb_emb_201: {
    canonicalId: 'cb_emb_201',
    code: 'CB-EMB-201',
    name: 'Embakasi 220kV Bus Coupler Breaker Q01',
    type: 'CIRCUIT_BREAKER',
    voltageKV: 220,
    substationId: 'embakasi',
    bayId: 'bay_emb_220_01',
    position: 'CLOSED',
    sf6PressureBar: 5.9,
    contactWearPct: 34.2,
    tripOperationsCount: 118,
    ratedCurrentA: 3150,
    interruptionCapacityKA: 50,
    operatingMechanism: 'SPRING',
    health: 72,
    risk: 54,
    state: 'WARNING',
    location: { latitude: -1.3211, longitude: 36.8924, region: 'NAIROBI' },
    source: 'SCADA_EMS',
    confidence: 95.8,
    reconciliationStatus: 'HIGH',
    sourceIds: {
      scadaId: 'SCD-CB-EMB-201',
      eamId: 'EAM-EQ-EMB-CB201'
    },
    timestamp: new Date().toISOString()
  }
};

export const CANONICAL_RELAYS: Record<string, ProtectionRelayEntity> = {
  rel_ssw_87l_01: {
    canonicalId: 'rel_ssw_87l_01',
    code: 'REL-SSW-87L-01',
    name: 'Suswa-Isinya Line Optical Differential Relay (87L)',
    type: 'PROTECTION_RELAY',
    voltageKV: 400,
    substationId: 'suswa',
    bayId: 'bay_ssw_400_01',
    relayModel: 'Siemens SIPROTEC 5 7SD87',
    scheme: 'LINE_DIFF_87L',
    redundancyScheme: 'MAIN_1',
    firmwareVersion: 'v9.32_IEC61850_ED2',
    gooseLatencyMs: 1.4,
    healthState: 'HEALTHY',
    lastTripTestTimestamp: '2026-06-14T08:00:00Z',
    health: 98,
    risk: 10,
    state: 'NORMAL',
    location: { latitude: -1.0543, longitude: 36.3532, region: 'RIFT_VALLEY' },
    source: 'WAMS_PMU',
    confidence: 99.7,
    reconciliationStatus: 'VERIFIED',
    sourceIds: {
      scadaId: 'SCD-REL-SSW-87L1',
      eamId: 'EAM-EQ-SSW-REL87L'
    },
    timestamp: new Date().toISOString()
  }
};

// ============================================================================
// CANONICAL GENERATION & LOAD INTERFACES
// ============================================================================
export const CANONICAL_GENERATION: Record<string, GenerationEntity> = {
  gen_olk_geo_iv: {
    canonicalId: 'gen_olk_geo_iv',
    code: 'GEN-OLK-IV',
    name: 'Olkaria IV Geothermal Power Plant (Units 1 & 2)',
    type: 'GENERATION',
    voltageKV: 400,
    substationId: 'olkaria',
    plantName: 'KenGen Olkaria IV',
    fuelType: 'GEOTHERMAL',
    installedCapacityMW: 150,
    currentDispatchMW: 148,
    spinningReserveMW: 12,
    rampRateMWPerMin: 5,
    governorStatus: 'ACTIVE',
    health: 97,
    risk: 12,
    state: 'NORMAL',
    location: { latitude: -0.8842, longitude: 36.3012, region: 'RIFT_VALLEY' },
    source: 'SCADA_EMS',
    confidence: 99.4,
    reconciliationStatus: 'VERIFIED',
    sourceIds: { scadaId: 'SCD-GEN-OLK4-01' },
    timestamp: new Date().toISOString()
  },
  gen_ltwp_310mw: {
    canonicalId: 'gen_ltwp_310mw',
    code: 'GEN-LTWP-310',
    name: 'Lake Turkana 310MW Wind Farm (365 Vestas Turbines)',
    type: 'GENERATION',
    voltageKV: 400,
    substationId: 'loiyangalani',
    plantName: 'Lake Turkana Wind Power Ltd',
    fuelType: 'WIND',
    installedCapacityMW: 310,
    currentDispatchMW: 295,
    spinningReserveMW: 0,
    rampRateMWPerMin: 25,
    governorStatus: 'DROOP',
    health: 94,
    risk: 22,
    state: 'NORMAL',
    location: { latitude: 2.7541, longitude: 36.7124, region: 'NORTH_EASTERN' },
    source: 'SCADA_EMS',
    confidence: 98.9,
    reconciliationStatus: 'VERIFIED',
    sourceIds: { scadaId: 'SCD-GEN-LTWP-01' },
    timestamp: new Date().toISOString()
  }
};

export const CANONICAL_LOADS: Record<string, LoadEntity> = {
  load_nbi_industrial: {
    canonicalId: 'load_nbi_industrial',
    code: 'LOAD-NBI-IND',
    name: 'Nairobi Industrial Area & SGR Inland Container Depot Feeder',
    type: 'LOAD',
    voltageKV: 66,
    substationId: 'embakasi',
    loadZoneName: 'Nairobi South East',
    customerClass: 'INDUSTRIAL',
    contractedDemandMW: 320,
    currentDemandMW: 298,
    powerFactor: 0.94,
    sheddingPriority: 'P2_ESSENTIAL',
    health: 85,
    risk: 68,
    state: 'NORMAL',
    location: { latitude: -1.3211, longitude: 36.8924, region: 'NAIROBI' },
    source: 'SCADA_EMS',
    confidence: 97.1,
    reconciliationStatus: 'VERIFIED',
    sourceIds: { scadaId: 'SCD-LD-NBI-IND' },
    timestamp: new Date().toISOString()
  }
};
