import type { FutureGridState, FutureGridYear } from './types';

export class TemporalGridModel {
  private static instance: TemporalGridModel | null = null;

  public static getInstance(): TemporalGridModel {
    if (!TemporalGridModel.instance) {
      TemporalGridModel.instance = new TemporalGridModel();
    }
    return TemporalGridModel.instance;
  }

  public getFutureGridStates(): FutureGridState[] {
    return [
      {
        year: '2026',
        temporalMode: 'FUTURE',
        demandForecastMw: 9300,
        generationCapacityMw: 9800,
        renewableCapacityMw: 3450,
        renewableSharePct: 36,
        reserveMarginPct: 17,
        congestionIndexPct: 42,
        n1CompliancePct: 92,
        transmissionLossPct: 4.4,
        installedSubstations: 49,
        newSubstations: 1,
        retiredAssets: 0,
        hvdcCapacityMw: 600,
        inertiaEstimateGws: 9.4,
        curtailmentRiskPct: 11,
        capacityMarginPct: 18,
        projectsCompleted: 4,
        projectsInProgress: 6,
        projectsPlanned: 9,
        evidence: [{
          source: 'Future grid digital twin',
          timestamp: new Date().toISOString(),
          modelVersion: 'grid-plan-v1.0',
          inputs: ['demand forecast', 'project pipeline', 'generation forecast'],
          assumptions: ['Demand trend remains stable under current policy and weather profile'],
          confidence: 0.81,
          dataState: 'MODELLED',
        }],
      },
      {
        year: '2027',
        temporalMode: 'FUTURE',
        demandForecastMw: 9950,
        generationCapacityMw: 10300,
        renewableCapacityMw: 3820,
        renewableSharePct: 39,
        reserveMarginPct: 15,
        congestionIndexPct: 52,
        n1CompliancePct: 90,
        transmissionLossPct: 4.6,
        installedSubstations: 50,
        newSubstations: 2,
        retiredAssets: 0,
        hvdcCapacityMw: 760,
        inertiaEstimateGws: 9.1,
        curtailmentRiskPct: 14,
        capacityMarginPct: 15,
        projectsCompleted: 5,
        projectsInProgress: 7,
        projectsPlanned: 9,
        evidence: [{
          source: 'Future grid digital twin',
          timestamp: new Date().toISOString(),
          modelVersion: 'grid-plan-v1.0',
          inputs: ['demand forecast', 'HVDC plan', 'renewables growth'],
          assumptions: ['Moderate renewable expansion continues'],
          confidence: 0.79,
          dataState: 'MODELLED',
        }],
      },
      {
        year: '2028',
        temporalMode: 'FUTURE',
        demandForecastMw: 10650,
        generationCapacityMw: 11180,
        renewableCapacityMw: 4300,
        renewableSharePct: 44,
        reserveMarginPct: 13,
        congestionIndexPct: 61,
        n1CompliancePct: 88,
        transmissionLossPct: 4.9,
        installedSubstations: 51,
        newSubstations: 2,
        retiredAssets: 1,
        hvdcCapacityMw: 860,
        inertiaEstimateGws: 8.8,
        curtailmentRiskPct: 18,
        capacityMarginPct: 13,
        projectsCompleted: 6,
        projectsInProgress: 8,
        projectsPlanned: 10,
        evidence: [{
          source: 'Future grid digital twin',
          timestamp: new Date().toISOString(),
          modelVersion: 'grid-plan-v1.0',
          inputs: ['load growth', 'network reinforcement plan'],
          assumptions: ['Load growth continues and scheduled projects remain on track'],
          confidence: 0.75,
          dataState: 'MODELLED',
        }],
      },
      {
        year: '2029',
        temporalMode: 'FUTURE',
        demandForecastMw: 11420,
        generationCapacityMw: 11990,
        renewableCapacityMw: 4880,
        renewableSharePct: 49,
        reserveMarginPct: 11,
        congestionIndexPct: 69,
        n1CompliancePct: 86,
        transmissionLossPct: 5.2,
        installedSubstations: 53,
        newSubstations: 3,
        retiredAssets: 1,
        hvdcCapacityMw: 950,
        inertiaEstimateGws: 8.4,
        curtailmentRiskPct: 23,
        capacityMarginPct: 11,
        projectsCompleted: 7,
        projectsInProgress: 8,
        projectsPlanned: 11,
        evidence: [{
          source: 'Future grid digital twin',
          timestamp: new Date().toISOString(),
          modelVersion: 'grid-plan-v1.0',
          inputs: ['renewable expansion forecast', 'transmission demand shift'],
          assumptions: ['Renewables penetration rises materially with regional shift'],
          confidence: 0.72,
          dataState: 'MODELLED',
        }],
      },
      {
        year: '2030',
        temporalMode: 'FUTURE',
        demandForecastMw: 12380,
        generationCapacityMw: 12950,
        renewableCapacityMw: 5600,
        renewableSharePct: 55,
        reserveMarginPct: 9,
        congestionIndexPct: 76,
        n1CompliancePct: 83,
        transmissionLossPct: 5.6,
        installedSubstations: 55,
        newSubstations: 4,
        retiredAssets: 2,
        hvdcCapacityMw: 1100,
        inertiaEstimateGws: 8.1,
        curtailmentRiskPct: 29,
        capacityMarginPct: 9,
        projectsCompleted: 8,
        projectsInProgress: 9,
        projectsPlanned: 12,
        evidence: [{
          source: 'Future grid digital twin',
          timestamp: new Date().toISOString(),
          modelVersion: 'grid-plan-v1.0',
          inputs: ['long-term investment plan', 'renewables + HVDC outlook'],
          assumptions: ['Long-term expansion planning requires additional investment and operational adaptation'],
          confidence: 0.68,
          dataState: 'MODELLED',
        }],
      },
    ];
  }
}

export const temporalGridModel = TemporalGridModel.getInstance();
